### ISSUE TITLE
New fields

### ISSUE THREAD

**Issue by gizburdt** [gizburdt/cuztom#150]
Possible new field types:
- Email
- URL
- IP
- Spinner (http://jqueryui.com/spinner/)
- Number
- Phone
- Gallery
- Multiple files

**Comment by cisnerosebastian** [comment]
How about a field "files" ? where you could upload multiple files (not just one like the "file" field that is currently available. Also may be add in the config options of this field a way to setup file extension formats that can be uploaded?

**Comment by gizburdt** [comment]
Closing, but used for reference in the future
