### ISSUE TITLE
Add Meta to Cuztom Taxonomies

### ISSUE THREAD

**Issue by MarioGiancini** [gizburdt/cuztom#188]
I create a custom post type that I'm looking to have some specialized taxonomies for.  In this case I created a cpt called "Show". Each show can have several "Guests".  I want the Guests to be non-hierarchal and to have a meta field that would allow me to upload a picture (or featured image for the "Guest" tag) so I can call that back in a Show post to display all the guests on the current show.

How do I add a meta field to the cuztom taxonomy (Guests), and how doI make it non-hierarchal (tag based, not category)?

I know this would create a metabox in the cuztom post type:

    $show->add_meta_box(
        'meta_box_id',
        'Meta Box Name',
        array(
            // ARRAY OF FIELDS HERE
        )
    );

Does the same work for taxonomies? Browsing through the class I saw a function called add_term_meta(), so is it this?:

    $guest->add_term_meta(
        'meta_box_id',
        'Meta Box Name',
        array(
            'name'          => 'guest_image',
            'label'           => 'Guest Image',
            'description'  => 'Featured Image of Guest',
            'type'            => 'image',
        )
    )

**Comment by gizburdt** [comment]
Added to the docs
