### ISSUE TITLE
White text in tinymce editor

### ISSUE THREAD

**Issue by everlast000** [gizburdt/cuztom#320]
I can't be the only one who has this problem ('cause this happens to me alot).

Whenever I make a bundle with a wysiwyg editor, the first editor appears to be correct. But when I click "add", the second box is there, but the textcolor appears white and the buttons disappear (only the editors AFTER the "add" button). 

I get the following css on inspect:

``.js .tmce-active .wp-editor-area {
color: #fff;
}``

Any ideas?

**Comment by anteprimorac** [comment]
This is related to #329 and #313. I'm working on solution for this issues.

**Comment by gizburdt** [comment]
@anteprimorac Awesome! :)

**Comment by everlast000** [comment]
Hi guys!

Is there any news on this? It doesn't seem to work yet, haha. For me, this is kind of the most used application (getting multiple wysiwyg boxes in repeatable or bundle).

**Comment by gizburdt** [comment]
No, sorry, very busy :(

**Comment by gizburdt** [comment]
Relative to this one: https://github.com/gizburdt/cuztom/issues/313. Conflicting ID's.
