### ISSUE TITLE
Use your own wrapper function for register

### ISSUE THREAD

**Issue by gizburdt** [gizburdt/cuztom#322]
You could do this before:

```$book = new Cuztom_Post_Type('book')```

After some strange bugs, I discovered this gave some problems, so now you need to do this:

```php
function cuztom_content_types() {
    $book = new Cuztom_Post_Type('book');
}
add_action('init', 'cuztom_content_types');
```

Some of you already did this, that's no problem. Just keep using the new method :)

**Comment by burton86** [comment]
in which case you have the problem ? and ... what type of problem ? ... 
i would understand in which case i have to use an action to register a new CPT ... :-)
thx

**Comment by gizburdt** [comment]
This isn't really a bug, it needs to be added to the wiki (see ticket label). You always need to wrap your own Cuztom code (registering stuff) within a add_action('init', ... )

**Comment by thesquaremedia** [comment]
i found out that this is the problem you can't use $post->ID to add into a default_value because init hook happens before anything. Maybe if the metaboxes could be added outside the init hook then we could access the $post->ID

**Comment by gizburdt** [comment]
Added to the docs
