### ISSUE TITLE
bundle 'Add' type:wysiwyg -> error

### ISSUE THREAD

**Issue by subsumo** [gizburdt/cuztom#329]
Getting this error when trying to 'Add' a new set using bundles:

functions.js:251 Uncaught TypeError: Cannot read property 'replace' of undefinedfunctions.js:251 (anonymous function)load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,plupload,json2&ver=3.9.1:2 n.extend.eachload-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,plupload,json2&ver=3.9.1:2 n.fn.n.eachfunctions.js:195 (anonymous function)load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,plupload,json2&ver=3.9.1:3 n.event.dispatchload-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,plupload,json2&ver=3.9.1:3 n.event.add.r.handle

new_item.find('tr').each(function() {

Uncaught TypeError: Cannot read property 'replace' of undefined

tinyMCEPreInit.mceInit[new_id].elements = tinyMCEPreInit.mceInit[new_id].elements.replace( last_id_regexp, new_id );

**Comment by anteprimorac** [comment]
That is the problem with wysiwyg. We create new element with some hacks because WP doesn't have a API for that. What version of WP you are using? We need to know that because there are fundamental changes across a versions.

**Comment by gizburdt** [comment]
Error is fixed in v3
