### ISSUE TITLE
Repeatable Field Add New at Beginning?

### ISSUE THREAD

**Issue by mediagin** [gizburdt/cuztom#331]
This might be more of a feature request than an issue but perhaps it's possible with a tweak.  When adding a repeatable item, would it be possible to have the new field added before the existing list instead at the end of the list.  This will put the new area closer to the "+Add" button.  When you have more than a few items, it can be a chore going back and forth.  Thanks.  Jim

**Comment by gizburdt** [comment]
Thanks for your input! :)
