### ISSUE TITLE
Date Field Within Bundle Decreases One Day With Each Publish

### ISSUE THREAD

**Issue by mediagin** [gizburdt/cuztom#332]
Well, this is a weird one.  I have a date field within a bundle.  The date decreases on each date field by one day each time I hit refresh.  I made a screencast of the action... http://1drv.ms/1CB8TSa.  Jim

**Comment by gizburdt** [comment]
Very weird indeed! Thank you

**Comment by mediagin** [comment]
![cuztom](https://cloud.githubusercontent.com/assets/10080274/5839956/ada9e9f8-a157-11e4-9b9f-59f50a42185c.gif)  Apologies.  The video link didn't work.  Here's a gif.

**Comment by gizburdt** [comment]
Fixed in v3, launching soon :)
