### ISSUE TITLE
new custom post type and   'taxonomies' => array( 'category', 'post_tag' )

### ISSUE THREAD

**Issue by mifalko** [gizburdt/cuztom#333]
Hello
While creating new custom post types using the register_cuztom_post_type, I got problem when I tried to link the  standard axonomiy Category to my post type : the following parameter inserted in $args :     'taxonomies' => array( 'category', 'post_tag' )
has no effect.
So I had to go back to the traditional register_post_type where there is no problem  activating the standard category 
br / Falko

**Comment by gizburdt** [comment]
Can you send me a pastebin link with your code?

**Comment by mifalko** [comment]
$test = register_cuztom_post_type(
                'cpt_test',
                array(
                   'labels' => array(
                        'name' => __( 'Tests' ),
                        'singular_name' => __( 'Test' ),
                        'view_item' => __( 'View Test' ),
                        ),
                   'supports' => array('title', 'author', 'editor',
'excerpt', 'comments', 'thumbnail' ),
                   'taxonomies' => array( 'category', 'post_tag' ),

                )
        );


2015-01-22 16:29 GMT+01:00 Gijs Jorissen <notifications@github.com>:

**Comment by gizburdt** [comment]
Sorry, working through old tickets, did you find a solution?
