### ISSUE TITLE
Bundle fields in TAB

### ISSUE THREAD

**Issue by burton86** [gizburdt/cuztom#335]
$post->add_meta_box(
	'caratteristiche',
	'Caratteristiche',
	array(
		'tabs',
		array(
			'Funzionali' => array(
				array(
			        'name'          => 'funzionali',
			        'label'         => 'Caratteristiche funzionali',
			        'type'          => 'wysiwyg'
			    )
			),
		    'Tecniche' => array(
		    	array(
					'bundle',
					array(
						array(
					        'name'          => 'tecniche_label',
					        'label'         => 'Etichetta',
					        'type'          => 'text'
					    ),
					    array(
					    	'name'          => 'tecniche_value',
					        'label'         => 'Valore',
					        'type'          => 'textarea'
					    )
				    )
				)
		    )
		)
	)
)
i'm trying to make two tab , one with bundle box ....
is it correct the code ?
this works on backend but how can i get the all the bundle data ?...

![cattura](https://cloud.githubusercontent.com/assets/6352972/6171765/097b5852-b2dd-11e4-8321-f1fd249a6def.JPG)
![cattura2](https://cloud.githubusercontent.com/assets/6352972/6171766/097c6a62-b2dd-11e4-8d92-b22602ab7904.JPG)

**Comment by gizburdt** [comment]
Can you access your database? Then look in the wp_postmeta table and look for the key starting with "_caratteristiche". Look what the full key is and then use get_post_meta( [id], [key], true)

**Comment by burton86** [comment]
Can i put another Bundle in the tab Accessori ?
How can i modify my add_meta_box() ? do i need any ID more  ?  ... where do i have to place it ?
