### ISSUE TITLE
User Meta

### ISSUE THREAD

**Issue by everlast000** [gizburdt/cuztom#339]
Is there any documentation for User Meta's? :)

**Comment by gizburdt** [comment]
Not yet, but you could look at the user meta class in the source files.

Adding user meta can be done like this:
```
new Cuztom_User_Meta($id, $title, $locations, $data = array())
```

Locations are the places you want the meta (only on create, edit or both): `array( 'show_user_profile', 'edit_user_profile' );`

Hope it helps :)

**Comment by everlast000** [comment]
I don't realy get it. Something like this (not working):

```<?php
$meta = new Cuztom_User_Meta($id, "Titel", 'edit_user_profile', $data = array(
	'name' => 'test',
	'label' => 'Test',
	'type' => 'text'
));
?>```

**Comment by moise** [comment]
Try like this:

<pre>
// add custom user fields
$user_fields = array(
	array(
		'name'  => 'address-1',
		'label' => __( 'Address label 1', 'sam' ),
		'type'  => 'text'
	),
	array(
		'name'  => 'address-2',
		'label' => __( 'Address label 2', 'sam' ),
		'type'  => 'text'
	),
);

// wp user locations show/edit already set in class
$user_metas = new Cuztom_User_Meta( 'em_user_meta',  __( 'Additional info', 'sam' ), array(), $user_fields );
</pre>

**Comment by gizburdt** [comment]
Added to the wiki
