### ISSUE TITLE
Post ID and text readonly

### ISSUE THREAD

**Issue by thesquaremedia** [gizburdt/cuztom#341]
Hi i was wondering if there was already a way to make a text field read only and if there was a way to pass the current post id into the metabox field. I am trying to create a read only field where i want to provide a shortcode for people to copy and paste on posts or pages.

**Comment by gizburdt** [comment]
Maybe you can try to create a hidden field and pass a default_value...

**Comment by thesquaremedia** [comment]
yes thats my intention to pass a default value but trying to pass $post->ID; into the default value of a text field i figured i could try and figure out how to make it readonly later but passing that variable wouldn't work. it doesn't come up on the admin meatbox. It has to be the idea of the current post being edited.

**Comment by gizburdt** [comment]
You can try `type="hidden"` instead of `type="text"`

**Comment by thesquaremedia** [comment]
hey so i figured out a way to add to the code ignored to create readonly inputs pretty easily how would be the best way to show you the edit. I am still wondering how to post the current post ID being edit into the field.

**Comment by gizburdt** [comment]
I think `$post` isn't set in the backend, maybe `$_GET['id']` or something like that.
