### ISSUE TITLE
WYSIWYG editors not showing in bundle

### ISSUE THREAD

**Issue by richardegil** [gizburdt/cuztom#342]
Some of my WYSIWYG editors are not displaying their content in either text or visual view. Not seeing any major errors and I am using the latest version of the library.

Seeing this in Chrome, Safari and IE. Have not check FF.

http://d.pr/i/6mqI

**Comment by evertslagter** [comment]
Any updates on this bug or has somebody found a solution? Is the problem with using numbers in textarea's id still valid in WP? The underscore bug was resolved in 3.1.6 (https://codex.wordpress.org/Function_Reference/wp_editor), Any updates would be great!

**Comment by anteprimorac** [comment]
I have it already fixed on another project, but currently I'm very busy. I could make a pull request in few days.

**Comment by evertslagter** [comment]
Nice, would love to see it fix. :+1:

**Comment by gizburdt** [comment]
@anteprimorac As always, nice job! :) Looking forward to the pull request.

**Comment by evertslagter** [comment]
I'm hesitated to ask, but any chance you've got a bit more time to do the pull request? It would be really appreciated :)

**Comment by gizburdt** [comment]
Related to #313. Closing.
