### ISSUE TITLE
PHP Fatal error:  Call to a member function add_rewrite_tag() on a non-object with Cuztom_Post_Type

### ISSUE THREAD

**Issue by moise** [gizburdt/cuztom#343]
Hello ,
I had a strange issue ... for the first time I used cuztom on a plugin instead of a theme and I got this Fatal error, doing a new Custom Post Type.

The code is simple :

<pre>
if ( ! defined( 'COREPATH' ) )
	define( 'COREPATH', plugin_dir_path( __FILE__ ) );

if ( ! defined( 'COREURI' ) )
	define( 'COREURI', plugin_dir_url( __FILE__ ) );

define( 'CUZTOM_URL', COREURI . '/includes/wp-cuztom/' );
define( 'CUZTOM_DIR', COREPATH . '/includes/wp-cuztom/' );

include CUZTOM_DIR . 'cuztom.php';

$timeline = new Cuztom_Post_Type('timeline');
</pre>

The error is:
<pre>
PHP Fatal error:  Call to a member function add_rewrite_tag() on a non-object in /wordpress/wp-includes/rewrite.php on line 51
</pre>

Using cuztom in the theme path no error occurs

any idea?
thank you

**Comment by gizburdt** [comment]
Hmmm, very strange indeed. I used Cuztom in a plugin before without errors. Will have a look at it later :)

**Comment by moise** [comment]
Hello giz,
thank your for your answer...I will check too...

**Comment by tormjens** [comment]
Its probably because the `$wp_rewrite` is not yet availiable. Try putting your post type init inside a action hook. `init` will probably suffice.

**Comment by moise** [comment]
Thank's Tormjens, with your suggestion now it work...however I think we need to find a more clean solution to make it working without hooks.

**Comment by gizburdt** [comment]
All the Cuztom code was inside an `add_action('init')`, but that wasn't very stable too. I agree with you it's cleaner when the user (developer) doesn't need to add his code in an `add_action`, will look at it in v3. Maybe to `doing_filter` function will help

**Comment by gizburdt** [comment]
Added to the docs
