### ISSUE TITLE
Perform checks on saving metabox's values, before updating the post?

### ISSUE THREAD

**Issue by lazharichir** [gizburdt/cuztom#344]
Hello,

I am converting my plugin into a better, enhanced version, and I am using Cuztom. But I have two questions:

1) Is Cuztom still in development or is it "dead" and won't be updated any longer?
2) How to do my own hard-coded php checks for a specific metabox for a specific CPT? As of now, it just saves whatever is in the $_POST, I want to confirm the value of the $_POST is what I want, if not, show a notice.

Looking forward to get some help on this!

Best regards,

L

**Comment by gizburdt** [comment]
Hi,

Cool you're looking into Cuztom!

1) The latest version (2.9.16) is stable, though there will always be bugs (see github issues), and no, it's definitely not dead. I'm still working on version 3.0, but i'm very busy recently, so it will take a while before it will be released.
2) You can pass arrays with data, shown in examples and wiki, but you still can pass a function, so you can handle stuff yourslef :)

If you have more question, please let me know!

**Comment by lazharichir** [comment]
awesome, some I can just use my usual manage_pages_custom_column hook and do the backend stuff myself and save it all in the database through update_post_meta(....)?

**Comment by gizburdt** [comment]
Yes, but it's all wrapped in Cuztom too..

**Comment by lazharichir** [comment]
Ok, so if I just want to update myself one field and leave cuztom deal with the rest just like it does right now. Is it possible or it must be everything or nothin?

**Comment by gizburdt** [comment]
Everything or nothing per metabox. But you can add filters per field..

**Comment by lazharichir** [comment]
Would you know how to? I need to run a function everytime my custom post
type gets updated, dont actually need to edit anything on this post but
more on the others it is linked to.

-Lazhar

Sent on the move, please excuse typos and brevity.

**Comment by gizburdt** [comment]
Then you can just use the `add_action('save_post')` hook.

**Comment by lazharichir** [comment]
This is my CPT save function so I can save a metabox's fields myself with my own checks. But it doesn't work I believe because of the NONCE check.

	/**
	 * Process the family relationships.
	 *
	 * @since    1.0.0
	 */
	public function save_animal_family( $post_id ) {

		if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
		if ( ! isset( $_POST['cuztom_nonce'] ) || ! wp_verify_nonce( $_POST['cuztom_nonce'], 'cuztom_meta' ) ) return;
		if ( ! current_user_can( 'edit_post' ) ) return;


	    if(is_array($_POST['cuztom[_progenies]'])) { 
	        update_progenies($post_id, $_POST['cuztom[_progenies]']);
	    } 


	    if(isset($_POST['cuztom[_mother]'])) {

	    	$mother = empty($_POST['cuztom[_mother]']) ? "removem" : $_POST['cuztom[_mother]'];

	        if($mother == "removem") { 
	            update_parent($post_id, esc_attr($mother), true);
	        }
	        else { 
	            update_parent($post_id, esc_attr($mother), false);
	        }

	    } else { update_post_meta($post_id, '_mother', ""); }


	    if(isset($_POST['cuztom[_father]'])) {

	    	$father = empty($_POST['cuztom[_father]']) ? "removef" : $_POST['cuztom[_father]'];

	        if($father == "removef") { 
	            update_parent($post_id, esc_attr($father), true);
	        }
	        else { 
	            update_parent($post_id, esc_attr($father), false);
	        }

	    } else { update_post_meta($post_id, '_father', ""); } 

	}

**Comment by gizburdt** [comment]
You really don't need all of the code, Cuztom will handle it for you. Just add a cuztom_meta_box with fields (see wiki) and it will be fixed..

**Comment by lazharichir** [comment]
I know, but I do need to have update_parent() and update_progenies() do their jobs whenever it gets updated. How could I do that in a simpler way?

**Comment by lazharichir** [comment]
Basically, each animal has a custom field: mother, father and progenies (array for the last one) so everytime one animal is updated as the parent of the other, I have to run my own function to update the other end.

If A gets updated with B as his father; I need my function to update B with A in the progenies.

**Comment by gizburdt** [comment]
On this line: https://github.com/gizburdt/cuztom/blob/master/classes/meta/meta_box.class.php#L142, there is an `apply_filters`, so you can so add_filter, pass some params, check if the field is the one you want to do something with.

Somethins like this:

```
add_filter('cuztom_post_meta_save', 'do_something', 10, 3);
function do_something($value, $field, $post_id) {
  if($field == '_mother' && !empty($value) {
    update_parent($post_id, 'data', true');
}
```

You need to check the code, this is just from memory.

**Comment by lazharichir** [comment]
Yes, it does what I want but the issue is now Cuztom doesn't save metaboxes anymore. Trying to see why but can't get my head around it.

**Comment by gizburdt** [comment]
I think you need to return the `$value` again

**Comment by gizburdt** [comment]
Did you succeed?
