### ISSUE TITLE
Taxonomy: add_term_meta image not Save SVG

### ISSUE THREAD

**Issue by burton86** [gizburdt/cuztom#345]
Hi ... 
in my functions.php i've added the support to svg with 

function cc_mime_types($mimes) {
  $mimes['svg'] = 'image/svg+xml';
  return $mimes;
}
add_filter('upload_mimes', 'cc_mime_types');

there's anything else that i have to do for save an SVG in a term meta of image type ?

**Comment by gizburdt** [comment]
Can you check if you can upload a svg in a native wordpress uploader (eg media u[loader)? If it works there, it's a problem with cuztom, if it isn't working there, your code doesn't work..

**Comment by burton86** [comment]
With POST native Featured Image it works great . It's the first test that i've tried .

**Comment by gizburdt** [comment]
Will have a look at it :)
