### ISSUE TITLE
Bundle with no item

### ISSUE THREAD

**Issue by cisnerosebastian** [gizburdt/cuztom#346]
Bundles is a great feature, but, once you set a set of fields as bundle, you are forced to at least load one item, right?

Lets say you create a set of fields as Bundle. Everything working perfect.

When you try to load one item, you load it perfect, and you have a +add button to add more items.

If you don't load any item, you still get 1 empty item. My question is, is there an option where you can have no items at all? (like optional, 0, 1, or more). Right now, you are forced to have at least 1 item (empty).

is my question clear?

**Comment by gizburdt** [comment]
Your question is clear :) It's not yet possible. May I ask why you want to show 0 items?

**Comment by cisnerosebastian** [comment]
Lets say we have a bundle of "children" (of a maried couple).

In this case, you may or not have children, so that field may be 0, or can be more.

is my example clear?

**Comment by gizburdt** [comment]
Very clear :) Like I said, it's not possible yet.. Added Enhancement label to this issue

**Comment by cisnerosebastian** [comment]
Perfect. Great work by the way. I can't wait to check on v3 tho..

**Comment by gizburdt** [comment]
Thanks! Me neither, but I'm too busy, hope I have some time to complete 3.0 soon :)
