### ISSUE TITLE
It is possibile to have a tab inside a bundle?

### ISSUE THREAD

**Issue by moise** [gizburdt/cuztom#347]
Like said in the title I was trying to set a tab inside a bundle but obviously, the way I tried, does not works. So, there is a way to make this? 
Thank you...

**Comment by gizburdt** [comment]
It's not possible in v2.9.x, I'm working on this for v3 :)

**Comment by moise** [comment]
Thank you gizburdt...your work and support is fast and awesome as always ;)

**Comment by gizburdt** [comment]
Thank you! :)
