### ISSUE TITLE
cuztom_post_meta_save filter on a bundle?

### ISSUE THREAD

**Issue by lazharichir** [gizburdt/cuztom#348]
Hello,

I have three different custom post types and two of them are linked to the main one. Imagine one ANIMAL type, one VET VISIT type, and one ACHIEVEMENT type. I use a bundle on the admin page of the animal type so the user can add several vet visits at once.

I then when to catch the field and value of this bundle during the *cuztom_post_meta_save* filter and instead of adding them in a meta, loop through the array and add new custom-typed posts.

However, bundles don't appear in the cuztom post meta save filter, and i I remove the *if( $field->in_bundle ) continue;* line, they don't appear as an array.

How can I pass the bundle as an array to this filter?

	/**
	 * Normal save method to save all the fields in a metabox
	 *
	 * @author 	Gijs Jorissen
	 * @since 	2.6
	 */
	function save( $post_id, $values )
	{
		foreach( $this->fields as $id => $field )
		{
			if( $field->in_bundle ) continue;
			
			$value = isset( $values[$id] ) ? $values[$id] : '';
			$value = apply_filters( "cuztom_post_meta_save_$field->type", apply_filters( 'cuztom_post_meta_save', $value, $field, $post_id ), $field, $post_id );

			$field->save( $post_id, $value, 'post' );
		}
	}

**Comment by gizburdt** [comment]
Hmm, that's a good one! Maybe this one?: https://github.com/gizburdt/cuztom/blob/master/classes/fields/bundle.class.php#L251-L252

This is where the bundle is saved.
