### ISSUE TITLE
Insert Bundle Dynamically

### ISSUE THREAD

**Issue by mrkcristiano** [gizburdt/cuztom#349]
Hi,

I have to migrate data from a non-WP database, and I need to insert Bundle Fields.
Is there a way to do that using add_post_meta ?

Thanks

**Comment by gizburdt** [comment]
Hi,

Unfortunately there isn't a function or something to add data. Maybe have a look in the source, so you can see how I parse and save the data. Have a look in classes/fields/bundle.php

**Comment by mrkcristiano** [comment]
It's easier than I thought hahah
I just filled an array and it worked with add_post_meta.

```php
$meta_value = array();
$dados = array(
        'nome_dependente'    => utf8_encode($nome),
        'grau_de_parentesco' => utf8_encode($parente),
        'data_de_nascimento' => strtotime($dataNasc)
);

array_push($meta_value, $dados);
add_post_meta($id, '_dados', $meta_value);
```

Thanks anyway!

**Comment by gizburdt** [comment]
Nice :)
