### ISSUE TITLE
Feature Request User Dropdown Field

### ISSUE THREAD

**Issue by fului** [gizburdt/cuztom#351]
As I'm not really good at using github and therefore can't add code to pull requests, I'll be adding it here, sorry

I needed to add a field to the add_meta_box function in cuztom, so I created a copy of the **term_select.class.php** file in the **fields** folder and changed it to pull the users from wp.

It seems to work, although someone might make it better.

If you wish, it would be cool if it was added to future versions of cuztom.

Below you'll find the code for **user_select.class.php** which is located in the **fields** folder.

```php
<?php

if( ! defined( 'ABSPATH' ) ) exit;

class Cuztom_Field_User_Select extends Cuztom_Field
{
	var $_supports_repeatable 	= true;
	var $_supports_ajax			= true;
	var $_supports_bundle		= true;
	
	var $dropdown;
	var $value;

	function __construct( $field, $parent )
	{
		parent::__construct( $field, $parent );

		$this->args = array_merge(
			array(
				'orderby'		=> 'ID',
				'class'			=> '',
			),
			$this->args
		);
		
		$this->args['class'] 	.= ' cuztom-input cuztom-select cuztom-user-select';
		$this->args['echo']		= 0;
	}

	function _output( $value )
	{
		$this->args['name'] 	= 'cuztom' . $this->pre . '[' . $this->id . ']' . $this->after . ( $this->repeatable ? '[]' : '' );
		$this->args['id']		= $this->id . $this->after_id;
		$this->args['selected'] = ( ! empty( $value ) ? $value : $this->default_value );
		$this->dropdown 		= wp_dropdown_users( $this->args );

		$output = $this->dropdown;

		$output .= $this->output_explanation();

		return $output;
	}
}
```

Remember to include the file in the function `private function includes()` located in the **cuztom.php** file.

```php
include( CUZTOM_DIR . 'classes/fields/user_select.class.php' );
```

**Comment by gizburdt** [comment]
Sorry, missed this one, very nice! :)
