### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by greabs** [gizburdt/cuztom#354]
I noticed there has not been allot of activity on this project. Is it still alive /actively maintained?

**Comment by gizburdt** [comment]
Hi,

The project is still alive, but I'm very busy at work. Another thing is I'm waiting for Term Meta in core, so I can build a wrapper around it and release version 3.0.

**Comment by greabs** [comment]
Judging by your swift reply it's very much alive , cool :+1: Thanks for the feedback & keep up the good work!

**Comment by gizburdt** [comment]
Thank you :)
