### ISSUE TITLE
Bundles with date meta field

### ISSUE THREAD

**Issue by greabs** [gizburdt/cuztom#356]
Hi , it looks like date fields in bundles are not saving. Is this a limitation of the bundled fields? using v. 2.9.17

Thanx!

**Comment by gizburdt** [comment]
Will have a look at it

**Comment by greabs** [comment]
Hi, thanx for the reply. I had a look at it and the problem and after some digging it looks like the Timepicker js addon causes the problem. The version used by cuztom is out of date.

**Comment by gizburdt** [comment]
Fixed in v3, launching soon! :)
