### ISSUE TITLE
Question: wordpress 4.4 and term_meta

### ISSUE THREAD

**Issue by thesquaremedia** [gizburdt/cuztom#357]
Are you guys using the native/core wordpress functions to add_term_meta or is that a custom function? i know from the beginining this class was supposed to make the usage of wordpress functioanility easier instead of adding custom function to do things wordpress doesnt. aside from the creation of the field_types. I just want to make sure the creation of the newly added term_meta is present in the latest version and that it is using the wordpress native/core functions.

**Comment by gizburdt** [comment]
Version 2.* uses a custom function. We're working on 3.* which will use core term functions.
