### ISSUE TITLE
Can't show single post type.

### ISSUE THREAD

**Issue by arifh28** [gizburdt/cuztom#359]
I have a cuztom post type in my theme. This is my cuztom post type code for post type : kegiatan, profil and survei. 
<?php

// Kegiatan

$kegiatan = register_cuztom_post_type( 'Kegiatan', array(
	'labels' => array(
		'name' => 'Kegiatan',
		'singular_name' => 'Kegiatan',
		'add_new' => 'Tambah Kegiatan',
		'add_new_item' => 'Tambah Kegiatan',
		'edit' => 'Sunting',
		'edit_item' => 'Sunting Kegiatan',
		'new_item' => 'Kegiatan',
		'view' => 'Lihat',
		'view_item' => 'Lihat Kegiatan',
		'search_items' => 'Cari Kegiatan',
		'not_found' => 'Tidak Ada Kegiatan',
		'not_found_in_trash' =>
			'Tidak Ada Kegiatan dalam sampah.',
		'parent' => 'Parent Kegiatan'
	),
        'public'             => true,
        'publicly_queryable' => true,
        'show_ui'            => true,
        'show_in_menu'       => true,
        'query_var'          => true,
        'rewrite'            => array( 'slug' => 'kegiatan' ),
        'capability_type'    => 'post',
        'has_archive'        => true,
        'hierarchical'       => false,

    'supports' => array( 'title', 'editor', 'thumbnail' ),
    'menu_icon' => 'dashicons-calendar-alt'
	));

$kegiatan->add_meta_box(
   'kegiatan_meta',
   'Detail Kegiatan',
    array(
        array(
            'name'          => 'tanggal_kegiatan',
            'label'         => 'Tanggal kegiatan',
            'description'   => 'Tanggal diselenggarakannya kegiatan.',
            'type'          => 'date'
         ),

        array(
            'name'          => 'jam_kegiatan',
            'label'         => 'Jam kegiatan',
            'description'   => 'Waktu diselenggarakannya kegiatan.',
            'type'          => 'time'
        ),

        array(
            'name'          => 'lokasi_kegiatan',
            'label'         => 'Lokasi kegiatan',
            'description'   => 'Lokasi diselenggarakannya kegiatan.',
            'type'          => 'text'
        )
      )
   );

// Kegiatan

$profil = register_cuztom_post_type( 'Profil', array(
    'labels' => array(
        'name' => 'Profil',
        'singular_name' => 'Profil',
        'add_new' => 'Tambah Profil',
        'add_new_item' => 'Tambah Profil',
        'edit' => 'Sunting',
        'edit_item' => 'Sunting Profil',
        'new_item' => 'Profil',
        'view' => 'Lihat',
        'view_item' => 'Lihat Profil',
        'search_items' => 'Cari Profil',
        'not_found' => 'Tidak Ada Profil',
        'not_found_in_trash' =>
            'Tidak Ada Profil dalam sampah.',
        'parent' => 'Parent Profil'
    ),
    'public'             => true,
    'publicly_queryable' => true,
    'show_ui'            => true,
    'show_in_menu'       => true,
    'query_var'          => true,
    'rewrite'            => array( 'slug' => 'profil' ),
    'capability_type'    => 'post',
    'has_archive'        => true,
    'hierarchical'       => false,

    'supports' => array( 'title', 'editor', 'thumbnail' ),
    'menu_icon' => 'dashicons-calendar-alt'
));

// Survei

$survei = register_cuztom_post_type( 'Survei', array(
    'labels' => array(
        'name' => 'Survei',
        'singular_name' => 'Survei',
        'add_new' => 'Tambah Survei',
        'add_new_item' => 'Tambah Survei',
        'edit' => 'Sunting',
        'edit_item' => 'Sunting Survei',
        'new_item' => 'Survei',
        'view' => 'Lihat',
        'view_item' => 'Lihat Survei',
        'search_items' => 'Cari Survei',
        'not_found' => 'Tidak Ada Survei',
        'not_found_in_trash' =>
            'Tidak Ada Survei dalam sampah.',
        'parent' => 'Parent Survei'
    ),
    'public'             => true,
    'publicly_queryable' => true,
    'show_ui'            => true,
    'show_in_menu'       => true,
    'query_var'          => true,
    'rewrite'            => array( 'slug' => 'survei' ),
    'capability_type'    => 'post',
    'has_archive'        => true,
    'hierarchical'       => false,

    'supports' => array( 'title', 'editor', 'thumbnail' ),
    'menu_icon' => 'dashicons-calendar-alt'
));

$survei->add_meta_box(
    'survei_meta',
    'Detail Survei',
    array(
        array(
            'name'          => 'lokasi_survei',
            'label'         => 'Lokasi survei',
            'description'   => 'Lokasi diselenggarakannya survei.',
            'type'          => 'text'
        ),
        array(
            'name'          => 'tipe_survei',
            'label'         => 'Tipe survei',
            'description'   => 'Tipe survei yang diselenggarakan.',
            'type'          => 'select',
            'options'       => 
                array(
                    'Pilkada'               => 'Pilkada',
                    '100 Hari Pemerintahan' => '100 Hari Pemerintahan',
                ),
        ),
        
    )
);

I have a problem when i show single-survei, every post type "survei" i redirect to 404 page. This is single-survei code.

<?php
/**
 * The template for displaying all single posts.
 *
 * @package ariffasco
 */

get_header(); ?>
    
    <div class="container"><div class="row">
            <div class="col-md-8">
                <div id="primary" class="content-area">
                    <main id="main" class="site-main" role="main">

                        <?php while ( have_posts() ) : the_post(); ?>

                            <?php get_template_part( 'content', 'single' ); ?>

                            <?php
                            // If comments are open or we have at least one comment, load up the comment template
                            if ( comments_open() || '0' != get_comments_number() ) :
                                comments_template();
                            endif;
                            ?>

                        <?php endwhile; // end of the loop. ?>

                    </main>
                </div>
            </div>
            <?php get_sidebar(); ?>
        </div></div>
<?php get_footer(); ?>

But, single-kegiatan or single-profil working fine.

**Comment by gizburdt** [comment]
Did you flush your redirects? You can do that by saving your permalinks settings.

**Comment by arifh28** [comment]
No, i didn't flush my redirects. How to set in permalink setting?

**Comment by gizburdt** [comment]
Just go to Settings > Permalinks and press save :)

**Comment by arifh28** [comment]
It's work. I press Save in Permalink Setting and problem is solved. But how to without press save in permalink setting?

**Comment by gizburdt** [comment]
This may help: https://codex.wordpress.org/Function_Reference/flush_rewrite_rules
