### ISSUE TITLE
Meta Keys start with _  cant get used in any other plugin

### ISSUE THREAD

**Issue by ErenPhayte** [gizburdt/cuztom#365]
Hi,

I realised all metakeys use the _  when creating a metabox. This is far from ideal, as we have plugins that do not recognise the meta keys i.e. Fantastic Elastic Search. So we can't index these fields as it doesn't want anything to do with "hidden" fields.

Is there a work around for this or to prevent the fields from registering with an _  and rather register them as an actual public field?

**Comment by gizburdt** [comment]
Hi,

Can you provide a little snippet of yout functions.php?
Then I can give you the right information (when possible).

Gijs

**Comment by ErenPhayte** [comment]
Hi,

What exactly are you looking for?  How the Metabox was setup? Here is an
extract - simplified it for brevity.


$postTypeDefinition = array('wealth_sense', 'Wealth Sense');

$postTypeProperties = array(
            'supports' => array('title', 'editor', 'excerpt', 'comments',
'author', 'thumbnail'),
            'has_archive' => true,
            'rewrite' => array('slug' => 'wealth-sense'),
            'public' => true
          );

        $financialWellnessPost = new \Cuztom_Post_Type($postTypeDefinition,
$postTypeProperties);


$financialWellnessPost->add_meta_box(
            'ws',
            'Wealth Sense Post',
            array(
                array(
                    'name' => 'content_type',
                    'label' => 'Content Type',
                    'type' => 'select',
                    'options' => array(
                        'video' => 'Video',
                        'questionnaire' => 'Questionnaire',
                        'article' => 'Article',
                        'calculator' => 'Calculator',
                        'slideshare' => 'SlideShare',
                    ),
                    'default_value' => 'article',
                ),
                array(
                    'name' => 'featured',
                    'label' => 'Featured Post?',
                    'description' => 'Check this box to have this article
featured on the home page.',
                    'type' => 'checkbox',
                ),
                array(
                    'name' => 'life_stage',
                    'label' => 'Life Stage',
                    'type' => 'multi_select',
                    'repeatable' => false,
                    'options' => array ('','','','',''),
                    'default_value' => 'Starting Out',
                ),
                array(
                    'name' => 'attitude',
                    'label' => 'Attitude',
                    'type' => 'multi_select',
                    'repeatable' => false,
                    'options' => $attitudesArr,
                    'default_value' => '2',
                ),
                array(
                    'name' => 'calculator_id',
                    'label' => 'Calculator',
                    'type' => 'select',
                    'repeatable' => false,
                    'options' => array ('','','','',''),
                    'default_value' => '0',
                ),
            )
        );



Regards,
Johan

**Comment by ErenPhayte** [comment]
In the database the field is then stored as  _ws_content_type, _ws_life_stage  etc. So Fantastic Elastic Search doesn't recognize these  as they have this function (and several other plugins have a similiar function):

function meta_fields(){

    global $wpdb;
    $keys = $wpdb->get_col("SELECT meta_key
                            FROM $wpdb->postmeta
                            GROUP BY meta_key
                            HAVING meta_key NOT LIKE '\_%'
                            ORDER BY meta_key" );
    if ( $keys ){
      natcasesort($keys);
    } else{
      $keys = array();
    }
    return $keys;
}

**Comment by gizburdt** [comment]
I think when you change name to id, it will already work:

array(
                    'id' => 'content_type',
                    'label' => 'Content Type',
                    'type' => 'select',
                    'options' => array(
                        'video' => 'Video',
                        'questionnaire' => 'Questionnaire',
                        'article' => 'Article',
                        'calculator' => 'Calculator',
                        'slideshare' => 'SlideShare',
                    ),
                    'default_value' => 'article',
                ),

**Comment by ErenPhayte** [comment]
Genius! that seems to do the trick! thanks so much!

**Comment by gizburdt** [comment]
No problem :)
