### ISSUE TITLE
how to set Term Meta for Cuztom 3.0?

### ISSUE THREAD

**Issue by iplaywind** [gizburdt/cuztom#367]
hi, I use the Cuztom 3.0 with WordPress 4.5.2, for the Term Meta, I have several steps as follow:
1, includ the php file and option file 
`include(get_template_directory() . '/inc-oome/cuztom-3.0/cuztom.php' );`
`include(get_template_directory() . '/inc-oome/cuztom-3.0/option-taxonomy.php' );`

2, the following is the code in option-taxonomy.php file.

```
$termmeta = register_cuztom_term_meta(
    'post_tag_id', 
	array('post_tag'), 
	array(
		array(
			'id'        => '_data_text_field',
			'type'      => 'text',
			'label'     => 'Text',
		),
		array(
			'id'            => '_data_textarea',
			'type'          => 'textarea',
			'label'         => 'Textarea',
		),
		
    ),
	array('add_form', 'edit_form')
);
```

But I could not get the filed in both add term page and edit term page, could you point the wrong code for me?

Thanks.

**Comment by gizburdt** [comment]
v3.0 is still in beta, I will have a look at this problem asap :)

**Comment by iplaywind** [comment]
Thanks, v3.0 is a great version, I wish you publish the stable version. Waiting for your best message.

**Comment by gizburdt** [comment]
Hi,

Pushed a fix, and this is the correct code (may change in the future):

```
$termmeta = register_cuztom_term_meta(
    'post_tag_id',
    array('category'),
    array(
        'fields' => array(
            array(
                'id'        => '_data_text_field',
                'type'      => 'text',
                'label'     => 'Text',
            ),
            array(
                'id'            => '_data_textarea',
                'type'          => 'textarea',
                'label'         => 'Textarea',
            ),
        )
    ),
    array('add_form', 'edit_form')
);
```

**Comment by iplaywind** [comment]
Hi, I change the code in option-taxonomy.php file, but there is still problem
1, there is no added filed in the 'add form' and 'edit form' page.
2, there is a error message when I click and open the 'screen-options' panel. The following is error message.
`Warning: Invalid argument supplied for foreach() in E:\xampp\htdocs\000OPTION\wp-content\themes\twentysixteen\inc-oome\cuztom-3.0\src\Gizburdt\Cuztom\Meta\Term.php on line 122`
![error](https://cloud.githubusercontent.com/assets/6620570/15813755/09fd28aa-2bf4-11e6-8740-4371b4b9215c.png)

**Comment by gizburdt** [comment]
Did you download the latest version of 3.0?
