### ISSUE TITLE
Retrieving data

### ISSUE THREAD

**Issue by mfwebmaster** [gizburdt/cuztom#368]
Hi 

I have this code in a meta box

$box = new Cuztom_Meta_Box(
    'data',
    'The New box', 
    'vehicles',
    
    array(
        array(
            'name'              => '_engine_size', 
            'label'             => 'Engine Size',
            'type'              => 'text',
        ),
        array(
            'name'              => '_fue_type',
            'label'             => 'Fuel type',
            'type'              => 'text',
        )
    )
);

This box is working fine but can not seem to recall the data on the front end. I am using this code to recall the data? 

<?php  echo $data = get_post_meta(get_the_ID(), '_engine_size', true);?>

**Comment by gizburdt** [comment]
I think if you change `name` to `id` it will work :)

**Comment by mfwebmaster** [comment]
nope did not do the trick

**Comment by mfwebmaster** [comment]
Hi 

Sorry it did work.  
I just reloaded the page in Wordpress and saved it again.

**Comment by gizburdt** [comment]
Awesome :)
