### ISSUE TITLE
Remove Cuztom::beautify in some cases

### ISSUE THREAD

**Issue by carlosagonzalez** [gizburdt/cuztom#372]
I am having an issue where a **selected** option in a Cuztom `'type' => 'select'` metabox displays in the Dashboard with all words capitalized, although correct capitalization displays on the public page.  Targeting via CSS is only successful with **text-transform:uppercase;** and **text-transform:lowercase;**, which are not desired.  **!important** is ineffectual as well.  I noticed in **classes/fields/select.class.php** the following:  `Cuztom::beautify( $name )` and wondered if this could be the cause.

I have encountered this display issue in various themes our office has created.

Thank you.

**Comment by gizburdt** [comment]
@carlosagonzalez Fixed :)
