### ISSUE TITLE
term_select doesn't display selected value in repeatable mode

### ISSUE THREAD

**Issue by adyr** [gizburdt/cuztom#373]
In term_select.class.php line 33 looks like this:
$this->args['name'] 	= 'cuztom' . $this->pre . '[' . $this->id . ']' . $this->after . **( $this->repeatable ? '[]' : '' )**;

But in field.class.php, function _repeatable_output has this line:
$this->after = '[]';

So, if $this->repeatable is true, the generated name will be cuztom[SOME_ID][][] and this in turn will feed an array as value on term_select.class.php line 35:
$this->args['selected'] = ( ! empty( $value ) ? $value : $this->default_value );

**Comment by gizburdt** [comment]
Thanks for the report :)

**Comment by gizburdt** [comment]
So, removing this: " ( $this->repeatable ? '[]' : '' )", would fix the issue you say? :)

**Comment by gizburdt** [comment]
If you can confirm again, I will fix it :)
