### ISSUE TITLE
Repeatable in tabs

### ISSUE THREAD

**Issue by hphioolen** [gizburdt/cuztom#376]
i'm trying to implement the 3.0 version. A, so it seems, standard implementation will not save data in any situation. I've tried different WP versions on different servers PHP version 5.5

I started off trying to upgrade from 2.9, first problems i encountered were issues with repeater fields in Tabs, they are also not working. So then i stripped down to basic functionality, but it will simply not save any data.

Example of the code used:
![schermafbeelding 2017-03-09 om 16 42 34](https://cloud.githubusercontent.com/assets/902818/23757557/765eb10e-04e7-11e7-9cd7-d0ef92dea86e.png)

`include( 'cuztom/cuztom.php' );

// 1. Film CPT
$film  = register_cuztom_post_type( 'Film', array(
		    'has_archive' => true,
		     'menu_icon'   => 'dashicons-editor-video',
		    'supports' => array( 'title', 'editor', 'thumbnail', 'excerpt' )
		) );

$box = register_cuztom_meta_box(
		'data',
		'film',
    array(
			'title' 	=> __('Data', 'cuztom'),  
    		'fields' 	=> array(
    				array(
       					'name'		=> '_data_example',
	           			'label'   => 'Example',
	           	 		'type'    => 'text',
	           	 		
	        		)
				)
    )
);`

**Comment by gizburdt** [comment]
`'name' =>` is deprecated for a long time, pelase use `'id' =>` for your fields

**Comment by hphioolen** [comment]
Very true... earlier i discovered that myself. I copied it from the readme.md 
there is al lot deprecated in the docs ;-)

Then i return to my original issue, hope you can assist...

I'm trying to use repeater fields inside tabs but that runs into errors:

`
$box = register_cuztom_meta_box(
    'BundleBox',
    'film',
    array(
        'title'     => 'Film informatie',
        
        		'fields' => array(

        array(
            'id'			=> uniqid(),
			'type'    => 'tabs',
            'panels'	=> array(
                array(
					'id' 			=> '_data_tabs_panel_1',
					'title'		=> 'Algemeen',
					'fields'	=> array(
																         							       
							      // Text
							        array(
							            'id'				=> '_data_text_field',
							            'type'				=> 'text',
							            'label'				=> 'Field Label',
							            'repeatable'		=> true,
							        ),
							         array(
							            'id'          => 'film-poster',
							            'label'         => 'Film poster',
							            'description'   => 'Deze foto wordt gebruikt in overzichten en aan de bovenkant van de pagina',
							            'type'          => 'image'
							         ),	
							         array(
								        'id'                    => '_youtube',
								        'type'                  => 'text',
								        'label'                 => __('Youtube'),
								        'description'           => __('Hierin staan de Youtube film links die gebruikt worden.<br> Je kunt hier eigen aan toevoegen en verslepen'),
								        'explanation'           => __('Voeg de URL van Youtube toe.'),
								        								
								         'repeatable'			=> false,       

								    ), 						      
							         										
					)
                ),
                array(
										'id' 			=> '_data_tabs_panel_2',
										'title' 	=> 'Tab Title',
										'fields'	=> array(
                    		
                    		
                    		 array(
								        'id'          => 'slider-home',
								        'label'         => 'Slider Home',
								        'description'   => 'Door aan te vinken wordt de film opgenomen in de homepage slider',
								        'type'          => 'checkbox',
								        
								        'show_admin_column'     => true,
								        'admin_column_sortable' => true,
								        
								     ),  
                    		
                    		
                    		
										)
                ),
            )
        )
		
		)
    )
);

`
 
This will result in a continuous spinning object and a JS error in the console:

warn — cuztom.min.js:1141[Vue warn]: Invalid expression. Generated function body:  (&&scope.list.length>=)||scope.loading
and additionally:
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

![schermafbeelding 2017-03-09 om 17 04 03](https://cloud.githubusercontent.com/assets/902818/23758541/6e4e58c2-04ea-11e7-9785-507aff923a0a.png)

**Comment by gizburdt** [comment]
I will have a look at it, thanks for the report :)

If you see anything in the docs that isn't right, please suggest an edit.

**Comment by gizburdt** [comment]
I found the reason of the bug, working on a fix

**Comment by gizburdt** [comment]
Can you test version 3.0.3? I think I fixed the problem
