### ISSUE TITLE
image field preview error

### ISSUE THREAD

**Issue by hphioolen** [gizburdt/cuztom#379]
Hi,

After selecting an image, the initial response is correct. 
However, after saving the preview is not shown a JS error is thrown and i can't remove the saved image

error on opening:

> TypeError: undefined is not an object (evaluating 'attachment.sizes.medium')

error on trying to change the image  (removing seems to work..)

> TypeError: null is not an object (evaluating 'this.uploader.open') 
![schermafbeelding 2017-03-15 om 11 32 39](https://cloud.githubusercontent.com/assets/902818/23944435/23fe607c-0973-11e7-8ff2-2181ae1cc07c.png)

`
$box = register_cuztom_meta_box(
    'BundleBox',
    'film',
    array(
        'title'     => 'Film informatie',
        
        		'fields' => array(
	        		
	        					 array(
							            'id'          => 'film-poster',
							            'label'         => 'Film poster',
							            'description'   => 'Deze foto wordt gebruikt in overzichten en aan de bovenkant van de pagina',
							            'type'          => 'image'
							         ),	
		
		)

    )
);
`

**Comment by gizburdt** [comment]
Thanks, will have a look at it

**Comment by hphioolen** [comment]
Thanks Gijs,

I think i was premature.. i found the error. The attachment "medium" is not saved on my localhost environment. So the thrown error is because of that. On my live server everything is working as expected. Sorry to trouble u!

**Comment by gizburdt** [comment]
NP! Thanks for the feedback :) 3.0 was a big update, so all feedback is welcome!
