### ISSUE TITLE
Bundles in tabs

### ISSUE THREAD

**Issue by hphioolen** [gizburdt/cuztom#380]
Hi Gijs,

I tried to add a bundle in a tab, which results in a similar error as with issue
#376 

JS error: 
[Vue warn]: Invalid expression. Generated function body:  (&&scope.list.length>=)||scope.loading

The code used:
`
$panel5 = 
//tabpanel
array(
	'id' 			=> '_data_tabs_panel_5',
	'title' 	=> 'Quotes',
	'fields'	=> array(
		//fields						
		array(
            'id'                => '_data_bundle',
            'label'             => 'Fields bundle',
            'type'              => 'bundle',
            'fields'			=> array(
                // Fields
               array(
		            'id'						=> '_data_textarea',
		            'type'					=> 'textarea',
		            'label'					=> 'Field Label',
		        ),
		        array(
		            'id'						=> '_data_textarea2',
		            'type'					=> 'textarea',
		            'label'					=> 'Field Label 3',
		        ), 
                
            )
            
            
	            
        ),
       								
								
	)
);
`

**Comment by gizburdt** [comment]
Forget to tell, yesterday.. uniqid() is causing problems. Can you set an ID yourself? I changed the docs already.

**Comment by hphioolen** [comment]
Just tried that, issue remains

**Comment by gizburdt** [comment]
Can you check version 3.0.4? Please let me know :)

**Comment by hphioolen** [comment]
Works!
