### ISSUE TITLE
Bundles issue with multiple metabox registrations

### ISSUE THREAD

**Issue by hphioolen** [gizburdt/cuztom#381]
Hi,

on creating multiple metaboxes in which one metabox has a bundle and the other one has a tab, either the tab has problems or the bundle has issues.

If i place the meta box with the bundle first, all fields after the image stop working, 

![schermafbeelding 2017-03-15 om 14 03 42](https://cloud.githubusercontent.com/assets/902818/23949698/9c38e37c-0988-11e7-808f-6a62452069ed.png)

If i place the meta box with the bundle last, the bundle stops showing up.

![schermafbeelding 2017-03-15 om 14 04 36](https://cloud.githubusercontent.com/assets/902818/23949676/83aaf4d0-0988-11e7-837a-c808cc7dd817.png)

Console log error:
[Vue warn]: Invalid expression. Generated function body:  (&&scope.list.length>=)||scope.loading

code:

`$box1 = register_cuztom_meta_box(
    'BundleBox1',
    'film',
    array(
        'title'     => 'Film Informatie',        
        'fields' => array(	        
	        
			//Tabs
	        array(
	            'id'			=> uniqid(),
				'type'    => 'tabs',
	            'panels'	=> array( $panel1, $panel2, $panel4,   )
				)
		)
    )
);

$box = register_cuztom_meta_box(
    'BundleBox2',
    'film',
    array(
        'title'     => 'Media Quotes',        
        'fields' => array(
	        
	      $panel5,
	        
		)
    )
);
`

$panel5 = 
//tabpanel
/*
array(
	'id' 			=> '_data_tabs_panel_5',
	'title' 	=> 'Quotes',
	'fields'	=> array(
		//fields	
*/					
		array(
            'id'                => '_data_bundle',
            'label'             => 'Fields bundle',
            'type'              => 'bundle',
            'fields'			=> array(
                // Fields
               array(
		            'id'						=> 'medium',
		            'type'					=> 'text',
		            'label'					=> 'Medium',
		        ),
		        array(
		            'id'            => '_data_select_sterren',
		            'type'          => 'select',
		            'label'         => 'Aantal Sterren',
		            'options'       => array(
		                'value1'    => '1',
		                'value2'    => '2',
		                'value3'    => '3',
		                'value4'    => '4',
		                'value5'    => '5'
		            ),
		        ),
		        array(
		            'id'						=> '_data_textarea2',
		            'type'					=> 'textarea',
		            'label'					=> 'Quote commentaar',
		        ), 
                
            )      
/*
        ),								
	)
*/
);

**Comment by gizburdt** [comment]
Forget to tell, yesterday.. uniqid() is causing problems. Can you set an ID yourself? I changed the docs already.

**Comment by hphioolen** [comment]
Just done that, does not resolve the issue

**Comment by gizburdt** [comment]
I think I already know a solution for all related problems, but I'm at work now, so can't fix them right away. Will start on it tonight (and hopefully finish tonight).

**Comment by hphioolen** [comment]
OK thanks for the update!

FYI the following works:

```
$box1 = register_cuztom_meta_box(
    'BundleBox1',
    'film',
    array(
        'title'     => 'Film Informatie',        
        'fields' => array(	        
	        $panel5,
			//Tabs
	        array(
	            'id'	=> '_filmtabs',
		   'type'    => 'tabs',
	            'panels'	=> array( $panel1, $panel2, $panel3, $panel4,   )
				),
		)
    )
);
```

but switching tab and bundle doesn't, (looks like the same problem):

```
$box1 = register_cuztom_meta_box(
    'BundleBox1',
    'film',
    array(
        'title'     => 'Film Informatie',        
        'fields' => array(	        
	   
			//Tabs
	        array(
	            'id'	=> '_filmtabs',
		    'type'    => 'tabs',
	            'panels'	=> array( $panel1, $panel2, $panel3, $panel4,   )
				),
				
			 $panel5,	
		)
    )
);
```

**Comment by gizburdt** [comment]
Can you check version 3.0.4? Please let me know :)

**Comment by hphioolen** [comment]
Checked, not resolved yet. #380 was resolved but this issue remains the same.

**Comment by gizburdt** [comment]
Because of the multiple errors with bundles, can you please provide me with the problems you have, and the complete snippet from your functions.php (the bundle part).

**Comment by hphioolen** [comment]
The problem remains the same as described above. The full code in functions.php:

`include( 'cuztom/cuztom.php' );

// 1. Film CPT
$film  = register_cuztom_post_type( 'Film', array(
		    'has_archive' => true,
		     'menu_icon'   => 'dashicons-editor-video',
		    'supports' => array( 'title', 'editor', 'thumbnail', 'excerpt' )
		) );



$panel1 =  array(
			'id' 			=> '_data_tabs_panel_1',
			'title'		=> 'Algemeen',
			'fields'	=> array(
				
			//Fields										         
				         array(
				            'id'          => 'film-oneliner',
				            'label'         => 'Oneliner',
				            'description'   => 'Onertitel van de film (in 1 regel)',
				            'type'          => 'textarea'
				         ),
				       
						 array(
					        'id'          => 'slider-home',
					        'label'         => 'Slider Home',
					        'description'   => 'Door aan te vinken wordt de film opgenomen in de homepage slider',
					        'type'          => 'checkbox',
					        
					        'show_admin_column'     => true,
					        'admin_column_sortable' => true,
					        
					     ),

				         array(
				            'id'          => 'film-poster',
				            'label'         => 'Film poster',
				            'description'   => 'Deze foto wordt gebruikt in overzichten en aan de bovenkant van de pagina',
				            'type'          => 'image'
				         ),	
				         array(
					        'id'                    => '_youtube',
					        'type'                  => 'text',
					        'label'                 => __('Youtube'),
					        'description'           => __('Hierin staan de Youtube film links die gebruikt worden.<br> Je kunt hier eigen aan toevoegen en verslepen'),
					        'explanation'           => __('Voeg de URL van Youtube toe.'),
					        								
					         'repeatable'			=> true,       

					    ), 
						     						      					         										
			)
        );

$panel2 =  array(
		'id' 			=> '_data_tabs_panel_2',
		'title' 	=> 'Film Gegevens (Filmdepot)',
		'fields'	=> array(
                    		
						// Fields                    		
            array(
	            'id'          => 'film-duur',
	            'label'         => 'Duur',
	            'description'   => 'De duur van de film',
	            'type'          => 'text'
	         ),
	         array(
	            'id'          => 'film-uitgave',
	            'label'         => 'Uitgave',
	            'description'   => 'Het jaar van uitgave van de film',
	            'type'          => 'text'
	         ),
	         array(
	            'id'          => 'film-release',
	            'label'         => 'Uitgave',
	            'description'   => 'premiere datum',
	            'type'          => 'text'
	         ),
	         array(
	            'id'          => 'film-land',
	            'label'         => 'Land',
	            'description'   => 'Het land waarin de film is geproduceerd',
	            'type'          => 'text'
	         ),
	         array(
	            'id'          => 'film-taal',
	            'label'         => 'Taal',
	            'description'   => 'De taal waar de film in wordt gesproken',
	            'type'          => 'text'
	         ),
	         array(
	            'id'          => 'film-ondertiteling',
	            'label'         => 'Ondertiteling',
	            'description'   => 'De taal van de ondertiteling van de film',
	            'type'          => 'text'
	         ),
	         array(
	            'id'          => 'film-regiseurs',
	            'label'         => 'Regie',
	            'description'   => 'Regie van de film',
	            'type'          => 'text'
	         ),
	         array(
	            'id'          => 'film-schrijvers',
	            'label'         => 'Schrijvers',
	            'description'   => 'Schrijvers van de film',
	            'type'          => 'text'
	         ),
	         array(
	            'id'          => 'film-cast',
	            'label'         => 'Cast',
	            'description'   => 'De cast van de film',
	            'type'          => 'textarea'
	         ),
	          array(
	            'id'          => 'film-stemmen',
	            'label'         => 'Stemmen',
	            'description'   => 'De stemmen cast van de film',
	            'type'          => 'textarea'
	         ),
	          array(
	            'id'          => 'film-distributor',
	            'label'         => 'Distributeur',
	            'description'   => '',
	            'type'          => 'text'
	         ),
	          array(
	            'id'          => 'film-producenten',
	            'label'         => 'Producenten',
	            'description'   => '',
	            'type'          => 'text'
	         ),		         
	         array(
	            'id'          => 'film_url_international',
	            'label'         => 'URL internationaal',
	            'description'   => '',
	            'type'          => 'text'
	         ),
	         array(
	            'id'          => 'film_url_netherlands',
	            'label'         => 'URL Nederland',
	            'description'   => '',
	            'type'          => 'text'
	         ),
	          array(
	            'id'          => 'film_url_extra',
	            'label'         => 'URL extra',
	            'description'   => '',
	            'type'          => 'textarea'
	         ),
	          array(
	            'id'          => 'film_classifications',
	            'label'         => 'Classificatie',
	            'description'   => '',
	            'type'          => 'text'
	         ),
	         array(
	            'id'          => 'film_tags',
	            'label'         => 'Tags',
	            'description'   => '',
	            'type'          => 'text'
	         ), 
						     
						      
            		
            		
            		
		)
   );


$panel3 =  //tabpanel
array(
	'id' 			=> '_data_tabs_panel_3',
	'title' 	=> 'Kijkwijzer data',
	'fields'	=> array(
		//fields 
		 array(
	        'id'            => 'smartmeta_kijk_radio',
	        'type'          => 'radios',
	        'label'         => 'Leeftijd',
			'options' => array(
						'kijk-al' => '<img src="' .plugins_url( 'img/BAL.png' , __FILE__ ).'" alt="alle leeftijden" />',
						'kijk-zes' => '<img src="' .plugins_url( 'img/B6.png' , __FILE__ ).'" alt="zes jaar en ouder" />',
						'kijk-negen' => '<img src="' .plugins_url( 'img/B9.png' , __FILE__ ).'" alt="negen jaar en ouder" />',
						'kijk-twaalf' => '<img src="' .plugins_url( 'img/B12.png' , __FILE__ ).'" alt="twaalf jaar en ouder" />',
						'kijk-zestien' => '<img src="' .plugins_url( 'img/B16.png' , __FILE__ ).'" alt="zestien jaar en ouder" />',
						),
			),
	     array(
	        'id'          => 'film-kijk-geweld',
	        'label'         => 'geweld',
	        'description'   => '<img src="' .plugins_url( 'img/geweld.png' , __FILE__ ).'" alt="alle leeftijden" width="37" />',
	        'type'          => 'checkbox'
	     ),
	      array(
	        'id'          => 'film-kijk-eng',
	        'label'         => 'eng',
	        'description'   => '<img src="' .plugins_url( 'img/angst.png' , __FILE__ ).'" alt="alle leeftijden" />',
	        'type'          => 'checkbox'
	     ),
	      array(
	        'id'          => 'film-kijk-sex',
	        'label'         => 'sex',
	        'description'   => '<img src="' .plugins_url( 'img/sex.png' , __FILE__ ).'" alt="alle leeftijden" />',
	        'type'          => 'checkbox'
	     ),
	      array(
	        'id'          => 'film-kijk-discriminatie',
	        'label'         => 'discriminatie',
	        'description'   => '<img src="' .plugins_url( 'img/discriminatie.png' , __FILE__ ).'" alt="alle leeftijden" />',
	        'type'          => 'checkbox'
	     ),
	      array(
	        'id'          => 'film-kijk-drugs',
	        'label'         => 'drugs',
	        'description'   => '<img src="' .plugins_url( 'img/drugs.png' , __FILE__ ).'" alt="alle leeftijden" />',
	        'type'          => 'checkbox'
	     ),
	      array(
	        'id'          => 'film-kijk-grof',
	        'label'         => 'grof',
	        'description'   => '<img src="' .plugins_url( 'img/grof.png' , __FILE__ ).'" alt="alle leeftijden" />',
	        'type'          => 'checkbox'
	     )

    )
);


$panel4 = 
//tabpanel
array(
	'id' 			=> '_data_tabs_panel_4',
	'title' 	=> 'Advanced',
	'fields'	=> array(
		//fields						
		array(
            'id'                => 'film-jewel',
            'label'             => 'Jewel ID',
            'description'           => __('Alleen aanpassen als je het ZEKER weet!'),
            'type'              => 'text',
            
	        'show_admin_column'     => true,
	        'admin_column_sortable' => true,		            
        ),
        array(
            'id'                => 'maccData',
            'label'             => 'Macc Data ID',
            'description'           => __('Dit is het Filmdepot nummer dat hoort bij deze film. Veranderen van dit nummer zorgt voor het ophalen van andere film gegevens. Normaal hoeft dit dus nooit aangepast te worden.'),
            'type'              => 'text',
        ),
         array(
            'id'              => 'film_changedate',
            'label'             => 'Verander datum, laatste wijzigingsdatum van Filmdepot',
            'description'       => __(''),
            'type'              => 'text',
        ),
        
        array(
	        'id'          => 'filmdepotCheck',
	        'label'         => 'Filmdepot Opgehaald',
	        'description'   => 'Als de filmdepot data is opgehaald staat dit vinkje aan. Zet uit (en sla op) om het volgende keer automatisch op te laten halen. <a href="#">Klik hier</a> om de data handmatig op te halen.',
	        'type'          => 'checkbox',
	        
	        'show_admin_column'     => true,
	        'admin_column_sortable' => true,
	     ),								
								
	)
);

$panel5 = 
//tabpanel
/*
array(
	'id' 			=> '_data_tabs_panel_5',
	'title' 	=> 'Quotes',
	'fields'	=> array(
		//fields	
*/					
		array(
            'id'                => '_data_bundle',
            'label'             => 'Fields bundle',
            'type'              => 'bundle',
            'fields'			=> array(
                // Fields
               array(
		            'id'						=> 'medium',
		            'type'					=> 'text',
		            'label'					=> 'Medium',
		        ),
		        array(
		            'id'            => '_data_select_sterren',
		            'type'          => 'select',
		            'label'         => 'Aantal Sterren',
		            'options'       => array(
		                'value1'    => '1',
		                'value2'    => '2',
		                'value3'    => '3',
		                'value4'    => '4',
		                'value5'    => '5'
		            ),
		        ),
		        array(
		            'id'						=> '_data_textarea2',
		            'type'					=> 'textarea',
		            'label'					=> 'Quote commentaar',
		        ), 
                
            )      
/*
        ),								
	)
*/
);


/**********************************
**
**	 Register Meta BOX (with fields above)
**
***********************************/
$box = register_cuztom_meta_box(
    'BundleBox2',
    'film',
    array(
        'title'     => 'Media Quotes',        
        'fields' => array(
	        
	      $panel5,
	        
		)
    )
);


$box1 = register_cuztom_meta_box(
    'BundleBox1',
    'film',
    array(
        'title'     => 'Film Informatie',        
        'fields' => array(	        
	        
			//Tabs
	        array(
	            'id'			=> '_filmtabs',
				'type'    => 'tabs',
	            'panels'	=> array( $panel1, $panel2, $panel4,   )
				)
		)
    )
);


`

**Comment by hphioolen** [comment]
sorry code functions fails

```
include( 'cuztom/cuztom.php' );

// 1. Film CPT
$film  = register_cuztom_post_type( 'Film', array(
		    'has_archive' => true,
		     'menu_icon'   => 'dashicons-editor-video',
		    'supports' => array( 'title', 'editor', 'thumbnail', 'excerpt' )
		) );



$panel1 =  array(
			'id' 			=> '_data_tabs_panel_1',
			'title'		=> 'Algemeen',
			'fields'	=> array(
				
			//Fields										         
				         array(
				            'id'          => 'film-oneliner',
				            'label'         => 'Oneliner',
				            'description'   => 'Onertitel van de film (in 1 regel)',
				            'type'          => 'textarea'
				         ),
				       
						 array(
					        'id'          => 'slider-home',
					        'label'         => 'Slider Home',
					        'description'   => 'Door aan te vinken wordt de film opgenomen in de homepage slider',
					        'type'          => 'checkbox',
					        
					        'show_admin_column'     => true,
					        'admin_column_sortable' => true,
					        
					     ),

				         array(
				            'id'          => 'film-poster',
				            'label'         => 'Film poster',
				            'description'   => 'Deze foto wordt gebruikt in overzichten en aan de bovenkant van de pagina',
				            'type'          => 'image'
				         ),	
				         array(
					        'id'                    => '_youtube',
					        'type'                  => 'text',
					        'label'                 => __('Youtube'),
					        'description'           => __('Hierin staan de Youtube film links die gebruikt worden.<br> Je kunt hier eigen aan toevoegen en verslepen'),
					        'explanation'           => __('Voeg de URL van Youtube toe.'),
					        								
					         'repeatable'			=> true,       

					    ), 
						     						      					         										
			)
        );

$panel2 =  array(
		'id' 			=> '_data_tabs_panel_2',
		'title' 	=> 'Film Gegevens (Filmdepot)',
		'fields'	=> array(
                    		
						// Fields                    		
            array(
	            'id'          => 'film-duur',
	            'label'         => 'Duur',
	            'description'   => 'De duur van de film',
	            'type'          => 'text'
	         ),
	         array(
	            'id'          => 'film-uitgave',
	            'label'         => 'Uitgave',
	            'description'   => 'Het jaar van uitgave van de film',
	            'type'          => 'text'
	         ),
	         array(
	            'id'          => 'film-release',
	            'label'         => 'Uitgave',
	            'description'   => 'premiere datum',
	            'type'          => 'text'
	         ),
	         array(
	            'id'          => 'film-land',
	            'label'         => 'Land',
	            'description'   => 'Het land waarin de film is geproduceerd',
	            'type'          => 'text'
	         ),
	         array(
	            'id'          => 'film-taal',
	            'label'         => 'Taal',
	            'description'   => 'De taal waar de film in wordt gesproken',
	            'type'          => 'text'
	         ),
	         array(
	            'id'          => 'film-ondertiteling',
	            'label'         => 'Ondertiteling',
	            'description'   => 'De taal van de ondertiteling van de film',
	            'type'          => 'text'
	         ),
	         array(
	            'id'          => 'film-regiseurs',
	            'label'         => 'Regie',
	            'description'   => 'Regie van de film',
	            'type'          => 'text'
	         ),
	         array(
	            'id'          => 'film-schrijvers',
	            'label'         => 'Schrijvers',
	            'description'   => 'Schrijvers van de film',
	            'type'          => 'text'
	         ),
	         array(
	            'id'          => 'film-cast',
	            'label'         => 'Cast',
	            'description'   => 'De cast van de film',
	            'type'          => 'textarea'
	         ),
	          array(
	            'id'          => 'film-stemmen',
	            'label'         => 'Stemmen',
	            'description'   => 'De stemmen cast van de film',
	            'type'          => 'textarea'
	         ),
	          array(
	            'id'          => 'film-distributor',
	            'label'         => 'Distributeur',
	            'description'   => '',
	            'type'          => 'text'
	         ),
	          array(
	            'id'          => 'film-producenten',
	            'label'         => 'Producenten',
	            'description'   => '',
	            'type'          => 'text'
	         ),		         
	         array(
	            'id'          => 'film_url_international',
	            'label'         => 'URL internationaal',
	            'description'   => '',
	            'type'          => 'text'
	         ),
	         array(
	            'id'          => 'film_url_netherlands',
	            'label'         => 'URL Nederland',
	            'description'   => '',
	            'type'          => 'text'
	         ),
	          array(
	            'id'          => 'film_url_extra',
	            'label'         => 'URL extra',
	            'description'   => '',
	            'type'          => 'textarea'
	         ),
	          array(
	            'id'          => 'film_classifications',
	            'label'         => 'Classificatie',
	            'description'   => '',
	            'type'          => 'text'
	         ),
	         array(
	            'id'          => 'film_tags',
	            'label'         => 'Tags',
	            'description'   => '',
	            'type'          => 'text'
	         ), 
						     
						      
            		
            		
            		
		)
   );


$panel3 =  //tabpanel
array(
	'id' 			=> '_data_tabs_panel_3',
	'title' 	=> 'Kijkwijzer data',
	'fields'	=> array(
		//fields 
		 array(
	        'id'            => 'smartmeta_kijk_radio',
	        'type'          => 'radios',
	        'label'         => 'Leeftijd',
			'options' => array(
						'kijk-al' => '<img src="' .plugins_url( 'img/BAL.png' , __FILE__ ).'" alt="alle leeftijden" />',
						'kijk-zes' => '<img src="' .plugins_url( 'img/B6.png' , __FILE__ ).'" alt="zes jaar en ouder" />',
						'kijk-negen' => '<img src="' .plugins_url( 'img/B9.png' , __FILE__ ).'" alt="negen jaar en ouder" />',
						'kijk-twaalf' => '<img src="' .plugins_url( 'img/B12.png' , __FILE__ ).'" alt="twaalf jaar en ouder" />',
						'kijk-zestien' => '<img src="' .plugins_url( 'img/B16.png' , __FILE__ ).'" alt="zestien jaar en ouder" />',
						),
			),
	     array(
	        'id'          => 'film-kijk-geweld',
	        'label'         => 'geweld',
	        'description'   => '<img src="' .plugins_url( 'img/geweld.png' , __FILE__ ).'" alt="alle leeftijden" width="37" />',
	        'type'          => 'checkbox'
	     ),
	      array(
	        'id'          => 'film-kijk-eng',
	        'label'         => 'eng',
	        'description'   => '<img src="' .plugins_url( 'img/angst.png' , __FILE__ ).'" alt="alle leeftijden" />',
	        'type'          => 'checkbox'
	     ),
	      array(
	        'id'          => 'film-kijk-sex',
	        'label'         => 'sex',
	        'description'   => '<img src="' .plugins_url( 'img/sex.png' , __FILE__ ).'" alt="alle leeftijden" />',
	        'type'          => 'checkbox'
	     ),
	      array(
	        'id'          => 'film-kijk-discriminatie',
	        'label'         => 'discriminatie',
	        'description'   => '<img src="' .plugins_url( 'img/discriminatie.png' , __FILE__ ).'" alt="alle leeftijden" />',
	        'type'          => 'checkbox'
	     ),
	      array(
	        'id'          => 'film-kijk-drugs',
	        'label'         => 'drugs',
	        'description'   => '<img src="' .plugins_url( 'img/drugs.png' , __FILE__ ).'" alt="alle leeftijden" />',
	        'type'          => 'checkbox'
	     ),
	      array(
	        'id'          => 'film-kijk-grof',
	        'label'         => 'grof',
	        'description'   => '<img src="' .plugins_url( 'img/grof.png' , __FILE__ ).'" alt="alle leeftijden" />',
	        'type'          => 'checkbox'
	     )

    )
);


$panel4 = 
//tabpanel
array(
	'id' 			=> '_data_tabs_panel_4',
	'title' 	=> 'Advanced',
	'fields'	=> array(
		//fields						
		array(
            'id'                => 'film-jewel',
            'label'             => 'Jewel ID',
            'description'           => __('Alleen aanpassen als je het ZEKER weet!'),
            'type'              => 'text',
            
	        'show_admin_column'     => true,
	        'admin_column_sortable' => true,		            
        ),
        array(
            'id'                => 'maccData',
            'label'             => 'Macc Data ID',
            'description'           => __('Dit is het Filmdepot nummer dat hoort bij deze film. Veranderen van dit nummer zorgt voor het ophalen van andere film gegevens. Normaal hoeft dit dus nooit aangepast te worden.'),
            'type'              => 'text',
        ),
         array(
            'id'              => 'film_changedate',
            'label'             => 'Verander datum, laatste wijzigingsdatum van Filmdepot',
            'description'       => __(''),
            'type'              => 'text',
        ),
        
        array(
	        'id'          => 'filmdepotCheck',
	        'label'         => 'Filmdepot Opgehaald',
	        'description'   => 'Als de filmdepot data is opgehaald staat dit vinkje aan. Zet uit (en sla op) om het volgende keer automatisch op te laten halen. <a href="#">Klik hier</a> om de data handmatig op te halen.',
	        'type'          => 'checkbox',
	        
	        'show_admin_column'     => true,
	        'admin_column_sortable' => true,
	     ),								
								
	)
);

$panel5 = 
//tabpanel
/*
array(
	'id' 			=> '_data_tabs_panel_5',
	'title' 	=> 'Quotes',
	'fields'	=> array(
		//fields	
*/					
		array(
            'id'                => '_data_bundle',
            'label'             => 'Fields bundle',
            'type'              => 'bundle',
            'fields'			=> array(
                // Fields
               array(
		            'id'						=> 'medium',
		            'type'					=> 'text',
		            'label'					=> 'Medium',
		        ),
		        array(
		            'id'            => '_data_select_sterren',
		            'type'          => 'select',
		            'label'         => 'Aantal Sterren',
		            'options'       => array(
		                'value1'    => '1',
		                'value2'    => '2',
		                'value3'    => '3',
		                'value4'    => '4',
		                'value5'    => '5'
		            ),
		        ),
		        array(
		            'id'						=> '_data_textarea2',
		            'type'					=> 'textarea',
		            'label'					=> 'Quote commentaar',
		        ), 
                
            )      
/*
        ),								
	)
*/
);


/**********************************
**
**	 Register Meta BOX (with fields above)
**
***********************************/
$box = register_cuztom_meta_box(
    'BundleBox2',
    'film',
    array(
        'title'     => 'Media Quotes',        
        'fields' => array(
	        
	      $panel5,
	        
		)
    )
);


$box1 = register_cuztom_meta_box(
    'BundleBox1',
    'film',
    array(
        'title'     => 'Film Informatie',        
        'fields' => array(	        
	        
			//Tabs
	        array(
	            'id'			=> '_filmtabs',
				'type'    => 'tabs',
	            'panels'	=> array( $panel1, $panel2, $panel4,   )
				)
		)
    )
);


```

**Comment by gizburdt** [comment]
I was able to reproduce the problem. I will have a look at it. Very strange problem :s

**Comment by gizburdt** [comment]
Could you try the latest master branch? Please let me know, if it all works I can tag a new version

**Comment by hphioolen** [comment]
this seems to be working!
