### ISSUE TITLE
Get page id in bundle function

### ISSUE THREAD

**Issue by hphioolen** [gizburdt/cuztom#385]
Hi,

i know this might be a little off topic, but maybe you have a solution:

For a function to couple fields to tickets i'm using a function that gets some metadata. For this i need the id of the edited page. A simple $_Get['post'] works. However, when i try to use this in a bundle it doesn't. 

My guess is that this is because in a bundle an ajax call is used to add the data fields, so the post id is nog available. Do you have any thoughts in how to get the post id to fill my object list? 

Code i use is:
The bundle:
```
$panel6 = 
//tabpanel
array(
	'id' 			=> '_data_tabs_panel_6',
	'title' 	=> 'Special',
	'fields'	=> array(
		
		//bundle
		array(
            'id'                => '_data_bundle_specials',
            'label'             => 'Fields bundle',
            'type'              => 'bundle',
            'fields'			=> array(
		
		//fields						
		array(
            'id'						=> '_special',
            'type'					=> 'radios',
            'label'					=> 'Soort Special',
            'options'       => array(

                'cineMore'    => 'Cine-More',
                'cineExpat'    => 'Cine-Expat'
            ),
        ),
		 array(
            'id'            => '_data_voorstelling',
            'type'          => 'select',
            'label'         => 'Voorstelling',
            'options'       => get_ticket_dates($id)
        ),				
		)
		)						
	)
);
```
And the function:
```
function get_ticket_dates($id) {
   
    global $post;
	$ticketvalues = array(); 	
	
	setlocale(LC_TIME, "nl_NL");
			
	$tickets = get_post_meta( $id, 'jewelfilm_shows', true );
                
     if ($tickets) {   

		$ticketvalues[0] = "Selecteer film tijd" ;
		   
		foreach ($tickets as $value ){
			
		
			$timestamp 		= strtotime($value["starts_at"]);
			
			$datum = strftime("%A %e %B", $timestamp);
			$tijd 			= date('H:i', $timestamp);
			
			//echo($value['starts_at']);
			$ticketvalues[$timestamp] =  $datum ." ". $tijd ;
			$i++;	
		}
		
	}
      
	return ($ticketvalues); 
    
}
```

**Comment by gizburdt** [comment]
Hi,

This is de data pushed with the bundle AJAX request:

array (size=3)
  'action' => string 'cuztom_add_bundle_item' (length=22)
  'security' => string '11810dd831' (length=10)
  'cuztom' => 
    array (size=5)
      'box' => string '' (length=0)
      'field' => string 'bundle1' (length=7)
      'object' => string '4' (length=1)
      'count' => string '3' (length=1)
      'index' => string '3' (length=1)

So you could use $_POST['cuztom']['object']

**Comment by hphioolen** [comment]
Thanks, works like a charm!

**Comment by gizburdt** [comment]
Nice :)
