### ISSUE TITLE
bundle & wysiwyg in 2.9

### ISSUE THREAD

**Issue by greabs** [gizburdt/cuztom#387]
Wysiwyg editors not showing in bundles is still an issue in 2.9

Can you provide a fix (or some pointers) for this problem in 2.9? 
I'm using this for an older project and as far as I can see migrating to 3.0 is (understandably) not as straight forward as I hoped.

Thanx!

related to #342

**Comment by gizburdt** [comment]
Will have a look at it :)

**Comment by greabs** [comment]
Thanx! Like I said, just some pointers as to what causes the problem will probably suffice!

**Comment by greabs** [comment]
Hi, any update on this? 
Thanx!

**Comment by gizburdt** [comment]
Will have a look at it soon. Sorry, very busy :(

**Comment by gizburdt** [comment]
Tried some things, but did not succeed. The codebase is just not clean and made for the future. Especially the javascript is a chaos. If you would like, I could help you with migrating to v3?
