### ISSUE TITLE
Bundle based on page id not showing

### ISSUE THREAD

**Issue by everlast000** [gizburdt/cuztom#389]
Version 3.0.5.

Bundles are working correctly whenever they are set for all posts in cpt, but when I check for a certain page id, the bundle won't display the fields and instead says **No items found**.

I use this to check for id:
`$post_id = $_GET['post'] ? $_GET['post'] : $_POST['post_ID'] ;
$template_file = get_post_meta($post_id,'_wp_page_template',TRUE);`

Either `if($template_file == "front-page.php"){`and `if($post_id == 12345678){`makes that the bundle is not working. 

Image without page id check: 
![image](https://cloud.githubusercontent.com/assets/4980700/24600168/a9fd3308-1853-11e7-9b55-e34384a2b367.png)

Image with page id check:
![image](https://cloud.githubusercontent.com/assets/4980700/24600192/bc753ff8-1853-11e7-9459-4397f4808655.png)

No console errors. What's up? :(

**Comment by everlast000** [comment]
Also, my bundles are not getting saved. Get the feeling there's something wrong. :(

**Comment by gizburdt** [comment]
Hi,

Thanks for the bug report :) Can you provide me with the complete snippet from your functions.php? (the part where you register the post type and metabox)

**Comment by everlast000** [comment]
Ofcourse!

`$post_id = $_GET['post'] ? $_GET['post'] : $_POST['post_ID'] ;
$template_file = get_post_meta($post_id,'_wp_page_template',TRUE);

$single = register_cuztom_post_type( "page" );
if($post_id == 2225){
	$single = register_cuztom_meta_box( 
	'Key Functions', 
	'page',
	array(
		'title'     => 'Key Functions',
		'id' 		=> 'key_functions',
		'fields' => array(
			array(
				'type'		=>	'bundle',
				'label'		=> 	'test',
				'fields' 	=> array(
					array(
						'id'		=>	'key_title',
						'label'		=>	'Title',
						'type'		=>	'text',
					),
					array(
						'id'		=>	'key_text',
						'label'		=>	'Text',
						'type'		=>	'textarea',
					),
					array(
						'id'		=>	'key_icon',
						'label'		=>	'Iconfont',
						'type'		=>	'text',
					),
				)
			)
		)
	)
);
}
`

**Comment by gizburdt** [comment]
Hi,

Found the problem. In the AJAX request the $_GET['post'] is not present. That's why I add the ID of the object (page) to the AJAX request. If you try this, it will work:

```php
$post_id = isset($_GET['post'])
        ? $_GET['post']
        : (isset($_POST['cuztom']['object']) ? $_POST['cuztom']['object'] : null);
```
