### ISSUE TITLE
Menu pages (settings pages)

### ISSUE THREAD

**Issue by gizburdt** [gizburdt/cuztom#39]
Just like with the meta boxes. The callback parameter can be an array with fields. So the page gets the fields just like the meta box

**Comment by thesquaremedia** [comment]
Hi i was wondering about the same i really like this frame work it combines a lot of things. Only thing it needs its being able to create A Theme Options section for it to be the best way to create themes.

**Comment by Pushplaybang** [comment]
Honestly can't wait for this feature Gizburdt, cuztom is amazing, and would take the cake! :)

**Comment by gizburdt** [comment]
You can use Option Tree for this: https://github.com/valendesigns/option-tree
