### ISSUE TITLE
wysiwyg not switching appropiately between visual and text

### ISSUE THREAD

**Issue by thesquaremedia** [gizburdt/cuztom#390]
have a site on versrion 4.7.3 of wordpress with cuztom 3.0.5 when cuztom is loaded it makes every wp editor break where the visual and text tabs do not work and create weird functionality.

**Comment by gizburdt** [comment]
Thanks, will have a look at it

**Comment by hphioolen** [comment]
I am experiencing the same. it does not seem to matter wether there are meta boxes registered. The editors won't switch between tex and visual mode and are very hard to edit. Do you have an idea how to resolve this? Or where to look for the solution?

**Comment by gizburdt** [comment]
I think here: https://github.com/gizburdt/cuztom/blob/master/resources/assets/js/cuztom-ui.js#L61-L69. Will have a look at it myself too, but very busy atm.

**Comment by hphioolen** [comment]
Yes that is the culprit, just i didn't check but is that piece complied into:
[https://github.com/gizburdt/cuztom/blob/master/assets/js/cuztom.min.js](url)
(line 13494-13505)
If i comment out the code in there everything works fine including extra added wysiwyg editors. 
I'm not sure wether this is obsolete or if you need it somewhere.

**Comment by thesquaremedia** [comment]
What is the purpose of reading the editor to all the work editors maybe. If you are adding the wysiwyg custom fields with the Wordpress wp_editor function I don't think you may need that line. In any case this article may help as to how to do it better. Or maybe you need to add a separate class to select the custom editors as to not affect the default wp ones. http://xu-li.github.io/wordpress/2016/03/14/add-tinyMCE-wordpres-bulk-edit/

**Comment by gizburdt** [comment]
Thanks guys :)

**Comment by thesquaremedia** [comment]
I just tested removing the compiled minified js you highlighted on the cuztom-ui.js and that indeed seems to fix the problem as mentioned by hphioolen. if there is no other reason why you added it i don't think you need it.

**Comment by gizburdt** [comment]
When I remove these lines, the editor buttons are not showing up

**Comment by hphioolen** [comment]
Are U sure? Because that is one of the issues i had with those lines included, while it's fine now!

**Comment by gizburdt** [comment]
You removed exactly these lines? https://github.com/gizburdt/cuztom/blob/master/resources/assets/js/cuztom-ui.js#L60-L69

**Comment by gizburdt** [comment]
Can you test the latest master branch? If it's fixed in this branch, I can tag a new release. Thanks again! :)

**Comment by hphioolen** [comment]
Will do!

**Comment by hphioolen** [comment]
Not quite right, your new version makes the original editor working again, but i've a setup with two additional editors as meta, they don't work in your new version. They do however work in my "commented" version.

**Comment by gizburdt** [comment]
Ok, one thing fixed then, the original editor. Can you give me your functions.php? (sorry if you already provided it on another ticket)

**Comment by hphioolen** [comment]
no problem: 
i did this
```
$slidebox = register_cuztom_meta_box(
    'ExtraContent',
    'page',
    array(
        'title'     => 'Slide Informatie',        
        'fields' => array(	        
	        
			array(
	            'id'          => 'Extra_afbeelding',
	            'label'         => 'Afbeelding',
	            'description'   => 'Deze foto wordt gebruikt links van de tekst',
	            'type'          => 'image'
	         ),	
	        array(
	            'id'          => 'content_breed',
	            'label'         => 'Subtekst',
	            'description'   => 'Tekst naast de afbeelding in brede kolom.',
	            'type'          => 'wysiwyg'
	         ),
	         
	         array(
	            'id'          => 'content_vervolg',
	            'label'         => 'Hoofdtekst',
	            'description'   => 'Tekst onder de brede balk.',
	            'type'          => 'wysiwyg'
	         ),
	       
 			
				
		)
    )
);
```

**Comment by hphioolen** [comment]
Funny thing is that i have a version in which the .min.js file wasn't minified. That made it easy to remove the lines.

**Comment by gizburdt** [comment]
Haha, yeah, sometimes I forget to run gulp --production.. -_-

**Comment by thesquaremedia** [comment]
hey so based on my test and clear cache if i remove the whole piece of js it just works both cuztom wysiwyg and regular wordpress you can type center and add media. your modified code at least doesn't break the wp_editor but the cuztom meta doesn't work as stated. im really thinking you may just not need it or at least you don't need it on the version of wp im testing on. the reason why it was breaking to begin with and is breaking now is becuase the class 'wp-editor-area' is still getting output on the textarea and i believe is that class that wordpress uses to initialize the editor. which would make sense why without the code the editor appears. now the one thing to keep in mind is that the tinymce shouldn't be moved after it is initiated. so a js may be needed to fire when the metabox gets moved in order to do what is doing in the updated version to first remove the editor and readd it.

**Comment by gizburdt** [comment]
I was testing with editors in bundles, your code has editors in boxes. That's why I thought it was already fixed. I tested with both types now, and I think it is fixed. Can you check the latest master branch?

**Comment by thesquaremedia** [comment]
fixed on my end with default and a wysiwg on a meta. no bundles tested

**Comment by hphioolen** [comment]
Yep mine works as well!

**Comment by thesquaremedia** [comment]
you do get the broken weird functionality if youy move the metabox but thats becuase of what i mentioned. so for now no one move a metabox with a wysiwyg field type lol

**Comment by hphioolen** [comment]
Yes i get the weird functionality as wel when the wysiwyg is inside a bundle, with or without moving, probably on construction of the element it goes wrong.

**Comment by gizburdt** [comment]
Thanks for the help guys!! @thesquaremedia I fixed that problem for when a bundle is moved. Will have a look at moving meta boxes
