### ISSUE TITLE
Bundle fields empty

### ISSUE THREAD

**Issue by greabs** [gizburdt/cuztom#391]
First off, thanx for fixing this in 3.0.4 :   
```
if(typeof tinymce !== 'undefined') {
        $('.wp-editor-area') 
...  tinymce.execCommand('mceAddEditor', true, editorId); ...
```

Was causing some nasty problems, but thats a bit off topic :)

I'm having an issue with the bundles in 3.0.4. They return empty: 

![image](https://cloud.githubusercontent.com/assets/4689257/25000518/e945c99e-2041-11e7-9e6a-bb06be502a73.png)

Here's my code:

```
$box = register_cuztom_meta_box(
			'data',
				$this->PostType,
				array(
				'title'  => __( 'Data', 'cuztom' ),
				'fields' => array(
					array(
						'id'     => '_data_bundle',
						'type'   => 'bundle',
						'fields' => array(
							array(
								'id'    => '_data_example',
								'label' => 'Example',
								'type'  => 'text',
							),
							array(
								'id'    => '_data_example2',
								'label' => 'Example2',
								'type'  => 'text',
							)
						)
					)
				)
			) );
```

Any ideas?

**Comment by greabs** [comment]
Small update. Also normal repeatable fields seem to have a problem ('repeatable' => true,) 
It looks like the self::$fields static var is empty?

**Comment by gizburdt** [comment]
Thanks for the report :) Will have a look at it!

**Comment by gizburdt** [comment]
I can't reproduce this issue. Some questions:
- Is your code above within an if?
- Do you get any Console/Network errors in Dev Tools?
- Did/do you use the id `_data_bundle` for another field?

**Comment by greabs** [comment]
Very sorry! This was indeed because of an 'if' statement. With the 2.x version I was checking for the post type before running the add meta fields code to prevent unnecessary overhead on load. However, since the bundle fields are retrieved by an ajax call, the if statement would always return negative. 

Seems to work ok now. 

One thing I am a little bit concerned about now, is that fact that all this is being called on every page load, regardless of post type. This is inheritable WordPress functionality, but with the old 2.x branch I could at least check myself what code should be called for what post type.. 
Though neglectable for smaller applications, I've noticed this can significantly slow down the backend of bigger websites. It's a bit off-topic, but any thoughts on this?

**Comment by gizburdt** [comment]
I did think about this topic while building 3.0. That is the weak part about Wordpress' admin-ajax. I will have a look at it again. Maybe work with (better) Request objects and check if the post type is a Cuztom post type.

The object ID (and I think post type too) is/are pushed within the AJAX request, so I think you could still check for it. 

Thanks for all the feedback, very happy with it :)
