### ISSUE TITLE
Cuztom and WPML

### ISSUE THREAD

**Issue by everlast000** [gizburdt/cuztom#397]
Hi!

I can't get cuztom to work with WPML. I'm getting the next error:

"Notice: Undefined index: icl_translations in [...] /cuztom/src/Meta/Box.php on line 160

Fatal error: Call to a member function outputColumnContent() on null in [...] /cuztom/src/Meta/Box.php on line 162"

Latest version Cuztom. Not using any translation.

```$box = register_cuztom_meta_box(
	    'section',
	    'page',
	    array(
			'id' 			=> '_section',
			'title' 	=> 'Section',
			'fields'	=> array(
				//bundle
				array(
		            'id'                => '_section',
		            'label'             => 'Section',
		            'type'              => 'bundle',
		            'fields'			=> array(
			
						//fields								
						array(
				            'id'					=> '_subtitle',
				            'type'					=> 'text',
				            'label'					=> 'Subtitle',
				        ),						
						array(
				            'id'					=> '_title',
				            'type'					=> 'text',
				            'label'					=> 'Title',
				        ),						
						array(
				            'id'					=> '_text',
				            'type'					=> 'text',
				            'label'					=> 'Text',
				        ),				
						array(
				            'id'					=> '_image',
				            'type'					=> 'image',
				            'label'					=> 'Image',
				        ),	
					)
				)						
			)
		)
	);```

How can I fix this?

**Comment by gizburdt** [comment]
Thanks for the report :)

**Comment by everlast000** [comment]
No problem! Do you have an easy way for fixing that error? Cuztom isn't working at all with WPML.

**Comment by thesquaremedia** [comment]
hey this is an error i helped fixed before and got reintroduced it has to do with  this two functions on that file
` public function addColumn($columns)
    {
        unset($columns['date']);

        foreach ($this->fields as $id => $field) {
            if ( isset( $field->show_admin_column ) &&  $field->show_admin_column) {
                $columns[$id] = $field->label;
            }
        }

        $columns['date'] = __('Date');

        return $columns;
    }

    /**
     * Used to add the column content to the column head.
     *
     * @param string $column
     * @param int    $postId
     */
    public function addColumnContent($column, $postId)
   {	
		if( isset( $this->fields[$column] ) ){
       		$field = $this->fields[$column];

       	echo $field->outputColumnContent();
		}else{
			return $column;
		}
	}`

cuztom interferes with the callbacks for third parties adding theiur own columns. there may still be an error on the addSortableColumn method for thirdparties adding sortable columns.

**Comment by gizburdt** [comment]
@thesquaremedia Maybe the error was fixed in 2.0? Or maybe it was not properly merged. Do you have a solution? If so, please create a PR :)

**Comment by thesquaremedia** [comment]
@gizburdt maybe because it wasn't properly merged it was done to a 3.0 version. do you want me to do the pull request to the master branch or the 3.0 branch?

**Comment by gizburdt** [comment]
@thesquaremedia Thanks for the PR, will merge! :)

You fixed it in the Term class earlier: https://github.com/gizburdt/cuztom/blob/master/src/Meta/Term.php#L134-L136

**Comment by gizburdt** [comment]
@everlast000 Can you check the latest version (3.1.4)?

**Comment by thesquaremedia** [comment]
@gizburdt yes that would make total sense lol. i think there may still be an issue with the sortable method but i haven't come accrossed it. maybe i can test sometime today by trying to add one from a test plugin. i will try to do so on both term and box classes.

**Comment by gizburdt** [comment]
Awesome! Thanks for the help :)

**Comment by gizburdt** [comment]
@everlast000 Is this bug solved?
