### ISSUE TITLE
Column content error

### ISSUE THREAD

**Issue by hphioolen** [gizburdt/cuztom#403]
HI, Just added Yoast to our site. They output SEO column to the admin overview, this results in an error on the output column from Cuztom. The following error is reported:

Fatal error: Call to a member function outputColumnContent() on a non-object in 
/assets/cuztom-master/src/Meta/Box.php on line 152

**Comment by gizburdt** [comment]
Thanks for the report. Will have a look at it. If you have a solution feel free to submit a PR :)

**Comment by thesquaremedia** [comment]
@hphioolen are you sure you have the latest release? what version of custom are you one? line 152 of the latest release is an opening php comment `/**` this should be fixed in the latest release.
