### ISSUE TITLE
Text Meta Field Repeatable | REST 

### ISSUE THREAD

**Issue by wiliam969** [gizburdt/cuztom#410]
Hello, 

first of all really nice work i love your addon. 

Generally Cuztom works for WP REST API but it would be very nice to just enable every meta field for the api instead of registering it via register_meta function of wp. 

Now to the real issue:

If you want to use the meta text field with the repeatable attribute it doesnt work correctly cause the metavalue is an array .

`Array to string conversion in ...\wp-includes\rest-api\fields\class-wp-rest-meta-fields.php</b> on line <b>431</b>`

**Comment by gizburdt** [comment]
Hi, 

Thanks for the issue, I didn't use the REST API before, so not really sure how it works. Repeatable fields are saved as serialized strings and are unserialized to an array when fetched from the database. This unserialization is done by Wordpress automaticly, so not sure ow to fix this. Would be awesome if the REST API auto converts an array to a string.

**Comment by wiliam969** [comment]
Ok.

I created a custom method now. Its just a temporary solution but it will work for those who get to the same problem. 

![image](https://user-images.githubusercontent.com/13550402/29456444-f20733e6-8415-11e7-99db-cd9b099b2045.png)

thank you for your quick help.
