### ISSUE TITLE
No Wordpress Admin after install

### ISSUE THREAD

**Issue by Jeff-B** [gizburdt/cuztom#411]
Hello,

I just install your last version 3.1.7 on WordPress 4.8.1. Now I have blank page instead of my admin or my website.

**Comment by gizburdt** [comment]
Could you enable debugging and tell me what error is showing?

**Comment by Jeff-B** [comment]
nothing in the debugger
blank page and <body></body>

**Comment by nicolaelitvac** [comment]
it might be because in bootstrap.php the path is not right.
try updating all lines to include **/src** in front of the path, ex:
`require_once __DIR__.'/Support/Guard.php';` to `require_once __DIR__.'/src/Support/Guard.php';`

**Comment by gizburdt** [comment]
I mean PHP debugging. White screen is mostly an error that isn't shown.

**Comment by Jeff-B** [comment]
i have the following error :

`Fatal error: require_once(): Failed opening required '/var/www/vhosts/zoo-host.com/chu.zoo-host.com/wp-content/themes/chu/inc/cuztom-3.1.7/src/Support/t/Notice.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/vhosts/zoo-host.com/chu.zoo-host.com/wp-content/themes/chu/inc/cuztom-3.1.7/bootstrap.php on line 8`

**Comment by gizburdt** [comment]
Could you send a tar of the files? I think I can't fix this in the comments section. Need to check it hands on

**Comment by Jeff-B** [comment]
Ok apparently Nicolae is right about the path. Now I don't have this blank page anymore.

**Comment by gizburdt** [comment]
Nice! :)

If you find something else, please let me know and open an issue :)

**Comment by Jeff-B** [comment]
Sure thanks for the quick answer.
