### ISSUE TITLE
Multiple instances of Cuztom

### ISSUE THREAD

**Issue by lapoguidi** [gizburdt/cuztom#413]
Hi Gijs,
I'm trying to install a selfmade Wordpress plugin I wrote for another template in a new template.
In the plugin I used Cuztom 3, unfortunately in the template they used Cuztom 2, so I have many "already declared" errors.
There's a way to use both in the same template? I thought to used function_exists, ecc. but I don't know if it's a good practice due the different version.
Could you help me?
Thank you very much.

**Comment by gizburdt** [comment]
This is a problem I thought of myself before, but wanted to wait till someone bumped into it. Unfortunately, I don't have a solution for v2 vs v3 problems. Is it possible to update v2 to v3?

**Comment by lapoguidi** [comment]
I can try to update v2 to v3, but can I solve that way?

**Comment by gizburdt** [comment]
I'm not 100% sure, sorry! In v4 I want to make Cuztom only available with composer, so this problem is solved.. I will try figure out a solution!

**Comment by lapoguidi** [comment]
Ok, thank you very much.
I'm trying to figure which files have the same name in v2 and v3.

**Comment by lapoguidi** [comment]
Hi again,
I found that cuztom v2 is used just marginally in template, so I just renamed:
register_cuztom_post_type to register_cuztom_post_type_v2 in cuztom/functions/post_type.php
and
register_cuztom_taxonomy to register_cuztom_taxonomy_v2 in cuztom/functions/taxonomy.php
Now it seems both live together... I done some tests and it seems to be all ok.
I'll check deeper during the new plugin (with cuztom v3) development.
Thanks for now.

NOTE: I keep it open so you can decide if close or keep open to post your solution, just in case.

**Comment by gizburdt** [comment]
Thanks for the research :)

I close it for now, if you find new stuff, please comment here :)
