### ISSUE TITLE
Custom taxonomies do not appear in term_select nor term_checkboxes fields

### ISSUE THREAD

**Issue by cisnerosebastian** [gizburdt/cuztom#419]
Am I doing something wrong?

$box = register_cuztom_meta_box(
        'data',
        'reporte',
        array(
            'title'  => __('Data', 'cuztom'),
            'fields' => array(
                array(
                    'id'    => '_data_term_select',
                    'type'  => 'term_select',
                    'label' => 'Field Label',
                    'args'  => array(
                        'taxonomy' => 'salida'
                    ),
                ),
            )
        )
    );

if I change "salida" to "category" that is a builtin taxonomy the code runs Perfect, but when I try any custom taxonomy like "salida" or any other taxonomy I've created with this same php class, the terms are not appearing in the select or the checkboxes, all empty.

any help on this?

**Comment by gizburdt** [comment]
I will have a look at it

**Comment by cisnerosebastian** [comment]
I've found out the problem. You may check on this and close it, or give it a look. The custom taxonomies i've created where not used in any post type, so, its count was 0. The terms didi not appeared on the select becouse of that, no empty terms appear on the select, only terms that have count more or equal 1.

**Comment by gizburdt** [comment]
Nice you found the solution :)
