### ISSUE TITLE
PostType addTaxonomy looks wrong

### ISSUE THREAD

**Issue by littlefyr** [gizburdt/cuztom#429]
I found this just looking at the code trying to sort things out. You docs are not always up to date with the code so looking at the code is sometimes easier. 

I generally prefer to create a post type and then add taxonomies to it rather than creating taxonomies and setting the post type. Semantics, I know but that's me. 

Anyways, I noticed that [`PostType.addTaxonomy`](https://github.com/gizburdt/cuztom/blob/master/src/Entities/PostType.php#L80) doesn't correctly use the taxonomy constructor: 

```
    public function addTaxonomy($name, $args = array(), $labels = array())
    {
        $taxonomy = new Taxonomy($name, $this->name, $args, $labels);
        return $this;
    }
```

whereas the [Taxonomy constructor](https://github.com/gizburdt/cuztom/blob/master/src/Entities/Taxonomy.php#L27) only has 3 arguments: 

```
    public function __construct($name, $postType = null, $args = array())
```

Now, if you pass the _right_ data in the second parameter to `addTaxonomy` its all good, which is probably why you never caught it, but someone is going to get hung up on it. 

[Oh and the docs for `addTaxonomy` are wrong (refers to `add_taxonomy`)](https://cuztom.readme.io/docs/post-type#section-add-taxonomy), although it doesn't reference the `$labels` parameter.

**Comment by gizburdt** [comment]
Thanks! Much appreciated! Will push fix in an few minutes
