### ISSUE TITLE
register_cuztom_user_meta $locations no location for new / create user screen

### ISSUE THREAD

**Issue by cisnerosebastian** [gizburdt/cuztom#430]
When adding custom user meta fields, there is a variable $locations to tell where these user meta fields will be shown, right now it's defaulted to array('show_user_profile', 'edit_user_profile') . This shows the user meta fields when viewing or editing the user.

I think there is no way, with this class, to show those user meta fields while creating the user, right?

**Comment by gizburdt** [comment]
Thanks for your question :) Wordpress doesn't support to add user meta to the create user form. Now, when I think about it, the locations parameter is unnecessary, since both will show the fields in the same location. 

Did this answer your question?

**Comment by cisnerosebastian** [comment]
yes, thanks.
