### ISSUE TITLE
Enabling new Gutenberg for custom post types

### ISSUE THREAD

**Issue by ghost** [gizburdt/cuztom#438]
Hi, I was wondering if you could let me know how to enable Gutenberg in your Cuztom post types.

**Comment by gizburdt** [comment]
Hi,

I didn't have the time to look at Gutenberg. How can I integrate Cuztom with Gutenberg?

**Comment by gizburdt** [comment]
Did some research, the following needs to be set in your CPT:

- supports needs to contains editor
- `show_in_rest => true` needs to be set
