### ISSUE TITLE
 bundle not displaying on the Frontend

### ISSUE THREAD

**Issue by mfwebmaster** [gizburdt/cuztom#448]
hi

here is my code for my bundle

```
> $box = register_cuztom_meta_box(
> 'order_item_info',
> 'orders',
> array(
>     'title'  => __( 'Oder Item Details', 'cuztom' ),
>     'fields' =>     array(
>         array(
>             'id'     => '_order_item_info_bundle',
>             'type'   => 'bundle',
>             'fields' => array(
>                     array(
> 						'id'    => '_order_101',
> 						'label' => 'Item Stock Code',
> 						'type'  => 'text',
>                     ),
>                     array(
>                         'id'    => '_order_102',
>                         'label' => 'Item Name',
>                         'type'  => 'text',
>                     ),
>                     array(
>                         'id'    => '_order_103',
>                         'label' => 'Item QTW',
>                         'type'  => 'text',
>                     )
>                 )
>             ),
>         )
>         
>     )
> );
```

I then add data to the metaboxes and it save the data.
![2019-10-30_9-08-25](https://user-images.githubusercontent.com/20338256/67836330-fcb20480-faf4-11e9-873d-6a56e70df3a6.jpg)

I been try and retrieve this on the front end with this code

`<?php echo $data = get_post_meta(get_the_ID(), '_order_item_info_bundle', true);?>`
![2019-10-30_9-10-21](https://user-images.githubusercontent.com/20338256/67836516-82ce4b00-faf5-11e9-8d8c-1ce4d8dd146f.jpg)

Please advive on a way forward.

**Comment by gizburdt** [comment]
If you var_dump() $data, you will see it's an array. So you have to loop through it.
