### ISSUE TITLE
Image with repeatable param not working

### ISSUE THREAD

**Issue by mfonsatti** [gizburdt/cuztom#449]
Hi,
i'm tryin to create an image field repeatable, but not working
![Schermata 2019-11-09 alle 15 41 04](https://user-images.githubusercontent.com/6352972/68530320-8341bf80-0307-11ea-8431-4acfda817ab4.png)

**Comment by gizburdt** [comment]
This bug is known to us. Unfortunately it can't be fixed without rewriting the complete Vue base of Cuztom.
